function T = sweep_h_channel_short_frames(userOpts)
%SWEEP_H_CHANNEL_SHORT_FRAMES Resumable short-frame H-channel sweep.
%
% Typical use:
%   addpath('E:\web_code\react\fft_project\react-fft\src\python');
%   T = sweep_h_channel_short_frames();
%
% Resume requires reusing an explicit outputDir:
%   opts = struct('outputDir','E:\ccsds_artifacts\h_run_01', ...
%       'includeLDPC',true,'Resume',true);
%   T = sweep_h_channel_short_frames(opts);

    if nargin < 1 || isempty(userOpts)
        userOpts = struct();
    end

    thisDir = fileparts(mfilename('fullpath'));
    addpath(thisDir);
    addpath(fullfile(thisDir, 'regression'));

    opts = localDefaultOptions(thisDir);
    opts = localMergeStruct(opts, userOpts);
    if isfield(userOpts, 'enableAdaptiveFastPhaseTracker') && ...
            ~isfield(userOpts, 'enableAdaptiveAPSKFastPhaseTracker')
        % Preserve the intuitive meaning of an explicit global A/B
        % override while keeping the safer APSK-only default otherwise.
        opts.enableAdaptiveAPSKFastPhaseTracker = logical( ...
            userOpts.enableAdaptiveFastPhaseTracker);
    end

    if opts.clearFunctionCache
        clear('run_ccsds_tm_evaluation');
        clear('HelperTMAPSKPilotlessFrontEnd');
        clear('HelperTMAPSKCarrierRecovery');
        clear('HelperTMAPSKFourthPowerCoarseCFO');
        clear('HelperTMAPSKMthPowerPhaseTracker');
        clear('HelperTMBlindReliabilityManager');
        clear('HelperTMComplexGainTracker');
        clear('HelperCCSDSTMDecoder');
        clear('HelperCCSDSTMDemodulator');
        clear('ccsdsTMWaveformGenerator');
        clear('satcom.internal.ccsds.tmBase');
    end

    codingCases = localBuildCodingCases(opts);
    channelCases = localBuildChannelCases(opts);
    cases = localBuildRunnerCases(opts, channelCases, codingCases);

    runnerOpts = struct( ...
        'OutputDir', opts.outputDir, ...
        'RunId', opts.RunId, ...
        'PlanVersion', "h-channel-short-v1", ...
        'Resume', opts.Resume, ...
        'MaxNewCases', opts.MaxNewCases, ...
        'RerunFailed', opts.RerunFailed, ...
        'BaseSeed', opts.randomSeed, ...
        'SeedMode', opts.SeedMode, ...
        'CaseIds', {opts.CaseIds}, ... % Keep struct scalar for cell IDs.
        'DryRun', opts.DryRun, ...
        'FailOnFailure', opts.FailOnFailure, ...
        'Verbose', opts.Verbose);
    [~, state] = reg_run_cases("h_channel_short", cases, runnerOpts);

    rows = cell(numel(cases), numel(localVariableNames()));
    for k = 1:numel(cases)
        meta = cases(k).Meta;
        record = state.Results(k);
        errorMessage = record.ErrorMessage;
        if strlength(errorMessage) == 0
            errorMessage = record.FailedChecks;
        end
        rows(k, :) = localMakeRow(k, meta.Channel, char(meta.ModType), ...
            meta.CodingCase, cases(k).Params, record, record.Success, ...
            record.Status, errorMessage, record.ElapsedTime);
    end
    T = cell2table(rows, 'VariableNames', localVariableNames());

    if ~opts.DryRun
        csvPath = fullfile(char(state.OutputDir), 'h_channel_short_sweep.csv');
        encodedFailPath = fullfile(char(state.OutputDir), ...
            'encoded_failure_details.csv');
        matPath = fullfile(char(state.OutputDir), 'h_channel_short_sweep.mat');
        localWriteTable(T, csvPath);
        encodedFailMask = string(T.Status) == "FAIL_METRIC" & ...
            ~strcmpi(string(T.ChannelCoding), "none");
        encodedFailColumns = { ...
            'Scenario','ModType','ChannelCoding','Rate', ...
            'BER','LockRate_pct','FER','EVM_post_pct','MER_dB', ...
            'CountedFrames','MatchedFrames','CMAMSE','DDMSE', ...
            'DDAcceptanceRate_pct','PredecoderBER', ...
            'PredecoderOffset','PredecoderPolarity', ...
            'PredecoderBitErrors','PredecoderBitsCompared', ...
            'PredecoderSteadyBER','PredecoderSteadyBitErrors', ...
            'PredecoderSteadyBitsCompared','PredecoderFramesCompared', ...
            'PredecoderFrameBERP95','PredecoderFrameBERMax'};
        encodedFailureDetails = T(encodedFailMask, encodedFailColumns);
        localWriteTable(encodedFailureDetails, encodedFailPath);
        localSaveFinalMat(matPath, T, opts, cases);
        fprintf('\n==== H-channel sweep state ====\n');
        fprintf('Checkpoint: %s\n', fullfile(char(state.OutputDir), 'checkpoint.mat'));
        fprintf('CSV       : %s\n', csvPath);
        fprintf('Encoded failures: %s\n', encodedFailPath);
        fprintf('MAT       : %s\n', matPath);
        localPrintWeakCases(T, opts);
    end
end

function cases = localBuildRunnerCases(opts, channelCases, codingCases)
    cases = struct('Id',{},'Name',{},'Category',{}, ...
        'Params',{},'Expected',{},'Meta',{});
    for iChannel = 1:numel(channelCases)
        channel = channelCases{iChannel};
        for iModulation = 1:numel(opts.modTypes)
            modulation = char(opts.modTypes{iModulation});
            for iCoding = 1:numel(codingCases)
                coding = codingCases{iCoding};
                if ~localIsCaseCompatible(modulation, coding, opts)
                    continue;
                end

                params = localBaseParams(opts);
                params.modType = modulation;
                params = localApplyModulationParams(params, modulation, opts);
                params = localApplyCodingParams(params, coding);
                params = localApplyChannelParams(params, channel, opts);

                name = sprintf('%s | %s | %s | %s', ...
                    channel.Name, modulation, coding.ChannelCoding, coding.RateLabel);
                id = "h." + localId(channel.Name) + "." + ...
                    localId(modulation) + "." + localId(coding.ChannelCoding) + ...
                    "." + localId(coding.RateLabel);
                sourceTag = localTMDataSourceCaseTag(params);
                if sourceTag ~= "random"
                    id = id + ".src." + localId(sourceTag);
                end
                expected = localExpected(opts, params, modulation);
                % The scalar fields below define the paired random-data
                % profile consumed by reg_run_cases.
                meta = struct( ...
                    'Channel', channel, ...
                    'ModType', string(modulation), ...
                    'CodingCase', coding, ...
                    'DataPathMode', string(params.DataPathMode), ...
                    'Modulation', string(modulation), ...
                    'Coding', string(coding.ChannelCoding), ...
                    'Rate', string(coding.RateLabel), ...
                    'RandomizerEnabled', logical(params.RandomizerEnabled), ...
                    'RandomizerFECPosition', string(params.RandomizerFECPosition), ...
                    'TMDataSource', string(params.TMDataSource), ...
                    'TMDataSourceI', string(params.TMDataSourceI), ...
                    'TMDataSourceQ', string(params.TMDataSourceQ));
                cases(end+1,1) = struct( ... %#ok<AGROW>
                    'Id', id, ...
                    'Name', string(name), ...
                    'Category', "h_channel", ...
                    'Params', params, ...
                    'Expected', expected, ...
                    'Meta', meta);
            end
        end
    end
end

function expected = localExpected(opts, params, modulation)
    required = ["BER","LockRate"];
    % OQPSK now reports staggered-I/Q rail MER. Continuous-phase MSK/GMSK
    % still have no ordinary constellation MER, so only those CPM modes
    % omit the MER requirement.
    usesConstellationMER = ~any(strcmpi(string(modulation), ...
        ["MSK","GMSK"]));
    if ~isempty(opts.minGoodMERdB) && usesConstellationMER
        required(end+1) = "MER_dB";
    end
    detector = "";
    if strcmpi(modulation, 'GMSK')
        detector = string(opts.GMSKDetectionMode);
        if detector == "official-viterbi-frame-reset"
            detector = "official";
        end
    end
    expected = struct( ...
        'RequiredMetrics', required, ...
        'MaxBER', opts.maxGoodBER, ...
        'MinLockRate', opts.minGoodLockPct / 100, ...
        'MaxFER', opts.maxGoodFER, ...
        'MinMERdB', localMetricThreshold(opts.minGoodMERdB, ...
            usesConstellationMER), ...
        'MinCountedFrames', opts.minCountedFrames, ...
        'ExpectedDataPathMode', string(params.DataPathMode), ...
        'ExpectedWaveformMode', string(params.WaveformMode), ...
        'ExpectedRandomizerFECPosition', string(params.RandomizerFECPosition), ...
        'ExpectedRandomizerEnabled', logical(params.RandomizerEnabled), ...
        'ExpectedGMSKDetector', detector, ...
        'ExpectedErrorIdentifier', "", ...
        'ExpectedErrorMessage', "");
end

function threshold = localMetricThreshold(value, enabled)
    if enabled
        threshold = value;
    else
        threshold = [];
    end
end

function opts = localDefaultOptions(thisDir)
    opts = struct();
    opts.channelFilePath = 'E:\matlab_project\v3.0\v3.0\channel\ChannelData.mat';
    opts.outputDir = '';
    % Keep each invocation independent without requiring the caller to
    % maintain a manual RunId.  Milliseconds avoid collisions when several
    % short sweeps are launched from one MATLAB session.
    stamp = clock;
    opts.RunId = sprintf('h_channel_short_%s_%03d', ...
        datestr(now, 'yyyymmdd_HHMMSS'), floor(1000*mod(stamp(6),1)));
    opts.Resume = true;
    opts.MaxNewCases = Inf;
    opts.RerunFailed = false;
    opts.CaseIds = strings(0,1);
    opts.DryRun = false;
    opts.FailOnFailure = false;
    opts.Verbose = true;
    % 多个已有 H 信道模型文件；默认空，表示只用 opts.channelFilePath
    opts.hModelCases = {};

    opts.modTypes = {'QPSK','UQPSK','8PSK','16APSK','32APSK','GMSK'};
    opts.convRates = {'1/2','2/3','3/4','5/6','7/8'};

    opts.includeNoHBaseline = true;
    % Optional no-H regression that still runs the adaptive equalizer.  The
    % legacy NoH_baseline bypasses equalization and therefore cannot detect
    % DD gate/step regressions or sector slips.
    opts.includeNoHEqualizedBaseline = false;
    opts.includeHEqualized = true;
    opts.includeNormHScenario = false;
    opts.includeNoEqualizerScenario = false;

    opts.includeUncoded = true;
    opts.includeConvolutional = true;
    opts.includeRS = false;
    opts.includeLDPC = false;
    opts.includeTurbo = false;
    opts.includeTPC = false;
    opts.ldpcRates = {'1/2'};
    opts.LDPCMaxIterations = 20;
    opts.turboRates = {'1/2'};
    opts.tpcCases = {struct('TPCCodeRate','1/2','TPCBlocksPerTF',8), ...
                     struct('TPCCodeRate','2/3','TPCBlocksPerTF',4)};

    opts.symbolRate = 10e6;
    opts.sps = 8;
    opts.snr = 30;
    opts.noisePlacement = 'afterChannel';
    % Physical link-budget default: fixed receiver noise PSD.  Use
    % noiseMode='snr' explicitly to reproduce the old measured-AWGN mode.
    opts.noiseMode = 'psd';
    opts.noisePSDdBmHz = -115.3;
    opts.noiseBandwidthHz = [];
    opts.cfo = 0;
    opts.carrierCaptureRangeHz = [];
    opts.phaseOffset = 0;
    opts.delay = 0;
    opts.RolloffFactor = 0.35;
    opts.hasASM = true;
    opts.RandomizerEnabled = false;
    opts.RandomizerFECPosition = 'afterEncoding';
    opts.DataPathMode = 'single';
    opts.TMDataSource = 'random';
    opts.TMDataSourceI = '';
    opts.TMDataSourceQ = '';
    opts.TMDataSourcePNInitialState = [];
    opts.TMDataSourcePNPolynomialExponents = [];
    opts.TMDataSourcePNInvert = false;
    opts.TMDataSourceFixedPattern = uint8(hex2dec('55'));
    opts.TMDataSourceIncrementStart = 0;
    opts.debugTMDataSource = false;
    opts.ConvolutionalG1G2Mode = 'auto-ccsds';
    opts.debugConvolutionalG1G2 = false;
    opts.WaveformMode = 'ordinaryTM';
    opts.NumBytesInTransferFrame = 1115;
    opts.forceNumBytesInTransferFrame = [];
    opts.berWarmUpFrames = 15;
    opts.berFrames = 30;
    % The generated warm-up frames settle synchronization/equalization and
    % are diagnostic only. Keep them out of the BER/FER acceptance window.
    opts.excludeBERWarmUpFrames = true;

    % The short H sweep is the default regression entry for the adaptive
    % receiver.  Known-H MMSE remains available as an explicit override.
    opts.equalizerMode = 'blind-cma-lms';
    opts.equalizerReg = [];
    opts.channelInterpolationMethod = 'linear';
    opts.channelOutOfRangeMode = 'wrap';
    opts.interpolateChannelDelays = false;
    opts.normalizeEqualizerOutput = true;

    % Keep the adaptive receiver configuration explicit in this sweep so
    % repeated runs do not silently inherit helper-file defaults.
    opts.adaptiveEqualizerTaps = 11;
    % Explicit timing-loop control for strict H-channel A/B tests.  Keep
    % the historical default until modulation-specific values are proven.
    opts.timingLoopBandwidth = 0.01;
    opts.apskTimingLoopBandwidth = 0.005;
    opts.adaptiveEqualizerBlindCostMode = 'auto';
    opts.adaptiveEqualizerPhaseOrder = 4;
    opts.adaptiveEqualizerCMAStep = 0.01;
    opts.adaptiveEqualizerDDStep = 1e-3;
    opts.adaptiveEqualizerCMAWarmupSymbols = 2000;
    opts.adaptiveEqualizerDDPasses = 1;
    opts.adaptiveEqualizerMaxTapNorm = 4;
    opts.adaptiveEqualizerMinCMAConfidence = 0.50;
    opts.adaptiveEqualizerRequireCMAConvergence = true;
    opts.adaptiveEqualizerQualityGuard = true;
    opts.adaptiveEqualizerMaxMSEDegradation = 0.10;
    opts.adaptiveEqualizerMSEDegradationMargin = 1e-3;
    opts.adaptiveEqualizerScalarSideTapOnRatio = 0.02;
    opts.adaptiveEqualizerDDWindowSymbols = 256;
    opts.adaptiveEqualizerDDMinWindowAcceptance = 0.75;
    opts.adaptiveEqualizerScalarDDPasses = 1;
    opts.adaptiveEqualizerEnableFadeHold = true;
    opts.adaptiveEqualizerEnableQAMWindowHold = false;
    opts.adaptiveEqualizerAutoScalarForQAM = false;
    opts.enableAdaptiveFastEnvelopeTracker = true;
    % Auto currently preserves the release IIR.  Select 'robust-block'
    % explicitly for the constellation-insensitive envelope A/B diagnostic.
    opts.adaptiveFastEnvelopeEstimatorMode = 'auto';
    opts.adaptiveFastEnvelopeTauSymbols = 64;
    opts.adaptiveFastEnvelopeBlockSymbols = 256;
    opts.adaptiveFastEnvelopeHopSymbols = 64;
    opts.adaptiveFastEnvelopeMedianBlocks = 3;
    opts.adaptiveFastEnvelopeTrimFraction = 0.05;
    opts.adaptiveFastEnvelopeGainSlewDBPerSymbol = 0.05;
    opts.adaptiveFastEnvelopeMinGainDB = -40;
    opts.adaptiveFastEnvelopeMaxGainDB = 100;
    % First-stage common reliability control.  Keep disabled by default
    % until A/B regression confirms that one blind pre-normalization HOLD
    % improves fades without changing NoH and mild-H baselines.
    opts.enableBlindReliabilityManager = false;
    opts.blindReliabilityWindowSymbols = 32;
    opts.blindReliabilityAcquireSymbols = 256;
    opts.blindReliabilityReferenceTauSymbols = 4096;
    opts.blindReliabilityFadeEnterDB = -12;
    opts.blindReliabilityFadeExitDB = -8;
    opts.blindReliabilityFadeEnterWindows = 2;
    opts.blindReliabilityRecoverWindows = 4;
    opts.blindReliabilityMaxInverseGainDB = 18;
    opts.debugBlindReliabilityManager = false;
    opts.enableAdaptiveFastPhaseTracker = true;
    % Normalized-H regression validates this feed-forward BPS + scalar
    % power-gain path for 16/32QAM.  The legacy post-BPS CMA cascade stays
    % disabled unless explicitly requested.
    % Empty lets the evaluator enable BPS only when H is active.  This keeps
    % the clean NoH constellation on its lower-EVM legacy synchronization
    % path while normalized-H cases automatically use BPS.
    opts.enableQAMBlindPhaseSearch = [];
    opts.QAMBlindPhaseSearch = struct();
    opts.enableQAMPowerGainTracker = true;
    opts.QAMPowerGainTracker = struct();
    opts.enableQAMPostBPSAdaptiveEqualizer = false;
    % Empty keeps the evaluator's automatic carrier-sync policy.  A scalar
    % false/true must be forwarded so APSK pilot-only carrier A/B tests are
    % real rather than silently ignored by the sweep wrapper.
    opts.enableAPSKQAMCarrierSync = [];
    opts.enableOQPSKHighRateTracking = true;
    opts.oqpskEnvelopeTauSymbols = 16;
    opts.oqpskHighRatePhaseWindowSymbols = 16;
    opts.enableUQPSKHighRateTracking = true;
    opts.enableUQPSKPostCarrierAdaptiveEqualizer = true;
    opts.enableUQPSKSecondPowerHighRatePhaseTracker = false;
    opts.enableUQPSKFourthPowerHighRatePhaseTracker = false;
    opts.enableUQPSKFFTCoarseCFO = false;
    opts.enableUQPSKDualBandwidthCarrierPLL = true;
    opts.uqpskCarrierAcquireLoopBW = 0.05;
    opts.uqpskCarrierTrackLoopBW = 0.02;
    opts.uqpskCarrierFadeThresholdDB = -12;
    opts.uqpskCarrierLockErrorThreshold = 0.12;
    opts.uqpskCarrierUnlockErrorThreshold = 0.40;
    opts.uqpskCarrierLockSymbols = 256;
    opts.uqpskCarrierUnlockSymbols = 128;
    opts.uqpskCarrierMinAcquireSymbols = 4096;
    opts.uqpskCarrierErrorTauSymbols = 64;
    opts.uqpskCarrierMaxFrequencyFraction = 0.10;
    opts.uqpskEnvelopeTauSymbols = 16;
    opts.uqpskHighRatePhaseWindowSymbols = 16;
    opts.uqpskEnvelopeMinGainDB = -40;
    opts.uqpskEnvelopeMaxGainDB = 100;
    % The free-running phase loop can select a wrong 32APSK quadrant.
    % Pilots plus ASM resolve APSK phase more reliably in the short sweep.
    opts.enableAdaptiveAPSKFastPhaseTracker = false;
    opts.enableAPSKCoarseFrequencyCompensator = true;

    % CCSDS ordinary-TM APSK production path is pilotless.  The older custom
    % pilot path remains available only through explicit legacy overrides.
    opts.APSKReceiverMode = 'pilotless';
    opts.enablePilotlessAPSKComplexGainTracker = true;
    opts.PilotlessAPSKCarrierRecovery = struct();
    opts.PilotlessAPSKComplexGainTracker = struct();
    opts.enablePilotlessAPSKPostFrontEndAdaptiveEqualizer = false;
    opts.debugPilotlessAPSK = false;

    opts.useTMAPSKPilots = false;
    opts.TMAPSKPilotInterval = 512;
    opts.TMAPSKPilotLength = 32;
    opts.TMAPSKPilotPreambleLength = 64;
    opts.TMAPSKPilotCorrectionMode = 'mmseinterp';
    opts.TMAPSKPilotPhaseSmoothWindow = 3;
    opts.TMAPSKPilotMMSERegularization = 0.01;
    opts.TMAPSKPilotMaxGainDB = 18;
    opts.TMAPSKPilotFadeThresholdDB = -12;
    opts.TMAPSKPilotFadeHold = true;
    opts.enableAPSKPilotFadeEqualizerHold = true;
    opts.facmWarmupFrames = [];
    opts.facmBERFrames = [];
    opts.facmNumIterations = [];
    opts.debugFACM = false;
    opts.enableFACMEqualizer = [];
    opts.facmEqualizerMode = '';
    opts.facmEqualizerReg = [];
    opts.facmEqualizerTaps = [];

    opts.gmskBT = 0.5;
    % The production evaluation entry point intentionally exposes only the
    % official continuous-phase Viterbi detector. Legacy detector helpers
    % may still be instantiated directly by an isolated debug script.
    opts.GMSKDetectionMode = 'official-viterbi-frame-reset';
    % Empty inherits the production default (enabled). Real H traces can
    % contain Doppler even when the separately injected opts.cfo is zero.
    opts.enableGMSKCoarseFrequencyCompensator = [];
    opts.enableGMSKResidualDopplerTracker = true;
    % The new PLL is opt-in so existing release baselines remain unchanged.
    % When enabled, run_ccsds_tm_evaluation bypasses the windowed tracker.
    opts.enableGMSKSecondOrderPLL = false;
    opts.gmskPLLAcquireLoopBandwidth = 0.020;
    opts.gmskPLLTrackLoopBandwidth = 0.003;
    opts.gmskPLLDetectorTauSymbols = 16;
    opts.gmskPLLLockErrorThreshold = 0.12;
    opts.gmskPLLUnlockErrorThreshold = 0.30;
    opts.gmskPLLLockSymbols = 128;
    opts.gmskPLLUnlockSymbols = 32;
    opts.gmskPLLMinAcquireSymbols = 256;
    opts.gmskPLLFadeThresholdDB = -15;
    opts.gmskPLLMaxFrequencyFraction = 0.05;
    opts.gmskResidualWindowSymbols = 1024;
    opts.gmskResidualHopSymbols = 256;
    opts.gmskResidualMedianWindows = 3;
    opts.gmskResidualMinConfidenceDB = 8;
    opts.gmskResidualMaxFrequencyFraction = 0.02;
    opts.enableCPMCoarseFrequencyCompensator = false;
    opts.debugMSK = false;
    opts.debugUQPSK = false;
    opts.gmskFrameResetASMMaxErrors = [];
    opts.gmskFrameResetASMMinGap = [];
    opts.gmskFrameResetMaxSearchFrames = 8;
    opts.gmskFrameResetMinSearchFrames = 2;
    opts.randomSeed = 1;
    % Keep each modulation/coding/data-path profile on the same random data
    % and noise realization across NoH and every H model.  Unlike the old
    % caseIndex mode, this also makes focused channel subsets comparable
    % with the full-channel sweep.
    opts.SeedMode = 'pairedChannelProfile';
    opts.clearFunctionCache = true;

    opts.debugCodedBoundary = true;
    % Persist the hard demodulator-vs-encoded-bit BER even when verbose
    % coded-boundary logging is disabled by the caller.
    opts.collectPredecoderStats = true;
    opts.predecoderMaxOffsetBits = 32;
    opts.debugFrameCheck = false;
    opts.debugFrameCheckCount = 20;
    opts.debugAllPerFrameBER = false;
    opts.debugPerFrameBERCount = 25;
    opts.debugPerFrameBERFormat = '';
    opts.debugPerFrameBERSummary = true;
    opts.debugPerFrameBERNonzeroCount = 16;
    opts.debugGMSK = false;
    opts.debugGMSKResidualTracker = false;
    opts.debugGMSKSecondOrderPLL = false;
    opts.gmskResidualDebugMaxWindows = 32;
    opts.debugASMPhase = true;
    % Optional sparse ASM phase anchoring.  These controls must be
    % forwarded explicitly: long coded cases can contain quadrant slips
    % after the historical 64-frame diagnostic prefix.
    % Empty delegates to the evaluator's modulation-aware policy: enable
    % sparse per-frame ASM phase anchoring for pilotless APSK on H only,
    % while leaving NoH, legacy APSK and other modulations unchanged.
    opts.enableASMFramePhaseCorrection = [];
    opts.asmFramePhaseCorrectionMaxError = 6;
    opts.asmFramePhaseCorrectionMinGap = 4;
    opts.asmFramePhaseCorrectionMinReliableFraction = 0.80;
    opts.debugASMPhaseTimelineFrames = 64;
    opts.debugEqualizerStats = true;
    opts.debugAdaptiveEqualizer = true;
    opts.debugSynchronizationChain = false;
    opts.debugSyncSegmentCount = 8;
    opts.debugCarrierRecovery = false;
    opts.debugHFrameStats = true;
    opts.debugHFrameStatsStart = 1;
    opts.debugHFrameStatsCount = 8;
    opts.debugCodedFrameSyncPrintLimit = 80;
    opts.enableCodedPhaseSearch = [];
    opts.phaseResolveFallback = [];
    opts.phaseResolveMode = '';

    opts.showFigures = false;
    opts.showPipelineFigure = false;
    opts.showDamageBudgetFigure = false;
    opts.showPowerFigure = false;
    opts.inputLevelDbm = -10;
    % Digital AGC is disabled for the historical sweep unless explicitly
    % enabled (the converter-chain path requires it). Keep the time constant
    % defined because localBaseParams always forwards it to the evaluator.
    opts.AGCEnabled = false;
    opts.AGCTimeConstantMs = 10;
    % Optional hardware-corresponding converter chain.  Disabled by default
    % to preserve historical regressions.  31 dB fixed gain minus 21 dB
    % attenuation maps -10 dBm input to approximately 0 dBm output and stays
    % below the documented +11 dBm output P1dB.
    opts.enableConverterChain = false;
    opts.upconverterFixedGainDB = 31;
    opts.upconverterAttenuationDB = 21;
    opts.downconverterFixedGainDB = 31;
    opts.downconverterAttenuationDB = 21;
    opts.downconverterAutoAttenuation = true;
    opts.downconverterTargetOutputDBm = 0;
    opts.converterAttenuationStepDB = 0.5;
    opts.converterMaxAttenuationDB = 30;
    opts.converterOutputP1dBDBm = 11;
    opts.converterInputMinimumDBm = -60;
    opts.converterInputMaximumDBm = -10;
    opts.enableConverterCompression = false;
    opts.enableADCEquivalent = false;
    opts.adcBits = 12;
    opts.adcFullScalePowerDBm = 0;
    opts.debugConverterChain = false;

    opts.maxGoodBER = 1e-3;
    opts.minGoodLockPct = 90;
    opts.minGoodMERdB = 18;
    opts.maxGoodFER = 0.20;
    opts.minCountedFrames = 1;

    if nargin > 0 && exist(fullfile(thisDir, 'run_ccsds_tm_evaluation.m'), 'file') ~= 2
        warning('sweep_h_channel_short_frames:MissingMain', ...
            'run_ccsds_tm_evaluation.m was not found next to this file.');
    end
end

function opts = localMergeStruct(opts, userOpts)
    if ~isstruct(userOpts)
        error('sweep_h_channel_short_frames:InvalidOptions', ...
            'userOpts must be a struct.');
    end
    names = fieldnames(userOpts);
    for i = 1:numel(names)
        opts.(names{i}) = userOpts.(names{i});
    end
end

function p = localBaseParams(opts)
    p = struct( ...
        'symbolRate', opts.symbolRate, ...
        'sps', opts.sps, ...
        'snr', opts.snr, ...
        'noisePlacement', opts.noisePlacement, ...
        'cfo', opts.cfo, ...
        'carrierCaptureRangeHz', opts.carrierCaptureRangeHz, ...
        'phaseOffset', opts.phaseOffset, ...
        'delay', opts.delay, ...
        'noiseMode', opts.noiseMode, ...
        'RolloffFactor', opts.RolloffFactor, ...
        'hasASM', opts.hasASM, ...
        'RandomizerEnabled', opts.RandomizerEnabled, ...
        'RandomizerFECPosition', opts.RandomizerFECPosition, ...
        'DataPathMode', opts.DataPathMode, ...
        'TMDataSource', opts.TMDataSource, ...
        'TMDataSourceI', opts.TMDataSourceI, ...
        'TMDataSourceQ', opts.TMDataSourceQ, ...
        'TMDataSourcePNInitialState', opts.TMDataSourcePNInitialState, ...
        'TMDataSourcePNPolynomialExponents', ...
            opts.TMDataSourcePNPolynomialExponents, ...
        'TMDataSourcePNInvert', opts.TMDataSourcePNInvert, ...
        'TMDataSourceFixedPattern', opts.TMDataSourceFixedPattern, ...
        'TMDataSourceIncrementStart', opts.TMDataSourceIncrementStart, ...
        'debugTMDataSource', opts.debugTMDataSource, ...
        'ConvolutionalG1G2Mode', opts.ConvolutionalG1G2Mode, ...
        'debugConvolutionalG1G2', opts.debugConvolutionalG1G2, ...
        'WaveformMode', opts.WaveformMode, ...
        'NumBytesInTransferFrame', opts.NumBytesInTransferFrame, ...
        'berWarmUpFrames', opts.berWarmUpFrames, ...
        'berFrames', opts.berFrames, ...
        'excludeBERWarmUpFrames', opts.excludeBERWarmUpFrames, ...
        'showFigures', opts.showFigures, ...
        'showPipelineFigure', opts.showPipelineFigure, ...
        'showDamageBudgetFigure', opts.showDamageBudgetFigure, ...
        'showPowerFigure', opts.showPowerFigure, ...
        'inputLevelDbm', opts.inputLevelDbm, ...
        'AGCEnabled', opts.AGCEnabled, ...
        'AGCTimeConstantMs', opts.AGCTimeConstantMs, ...
        'timingLoopBandwidth', opts.timingLoopBandwidth, ...
        'LDPCMaxIterations', opts.LDPCMaxIterations);

    % Optional I/Q-specific source conventions are forwarded only when the
    % caller supplies them, keeping the common configuration compact.
    sourceOverrideFields = { ...
        'TMDataSourcePNInitialStateI','TMDataSourcePNInitialStateQ', ...
        'TMDataSourcePNPolynomialExponentsI', ...
        'TMDataSourcePNPolynomialExponentsQ', ...
        'TMDataSourcePNInvertI','TMDataSourcePNInvertQ', ...
        'TMDataSourceFixedPatternI','TMDataSourceFixedPatternQ', ...
        'TMDataSourceIncrementStartI','TMDataSourceIncrementStartQ'};
    for iField = 1:numel(sourceOverrideFields)
        fieldName = sourceOverrideFields{iField};
        if isfield(opts, fieldName) && ~isempty(opts.(fieldName))
            p.(fieldName) = opts.(fieldName);
        end
    end

    converterFields = { ...
        'enableConverterChain', ...
        'upconverterFixedGainDB','upconverterAttenuationDB', ...
        'downconverterFixedGainDB','downconverterAttenuationDB', ...
        'downconverterAutoAttenuation','downconverterTargetOutputDBm', ...
        'converterAttenuationStepDB','converterMaxAttenuationDB', ...
        'converterOutputP1dBDBm','converterInputMinimumDBm', ...
        'converterInputMaximumDBm','enableConverterCompression', ...
        'enableADCEquivalent','adcBits','adcFullScalePowerDBm', ...
        'debugConverterChain'};
    for converterIndex = 1:numel(converterFields)
        converterName = converterFields{converterIndex};
        if isfield(opts, converterName) && ~isempty(opts.(converterName))
            p.(converterName) = opts.(converterName);
        end
    end

    adaptiveFields = { ...
        'adaptiveEqualizerTaps', ...
        'asmTrainingEqualizerTaps', ...
        'asmTrainingNLMSMu','asmDDNLMSMu', ...
        'asmNLMSRegularization','asmDDDecisionGate', ...
        'asmNLMSFadeThresholdDB','asmNLMSMaxTapNorm', ...
        'asmTrainingQualityGuard','asmTrainingMinScoreImprovement', ...
        'asmLocatorMinScore', ...
        'asmLocatorSearchRadiusSymbols','asmLocatorMaxOccurrences', ...
        'adaptiveEqualizerBlindCostMode', ...
        'adaptiveEqualizerPhaseOrder', ...
        'adaptiveEqualizerCMAStep', ...
        'adaptiveEqualizerDDStep', ...
        'adaptiveEqualizerDecisionGate', ...
        'adaptiveEqualizerCMASwitchMSE', ...
        'adaptiveEqualizerCMAWarmupSymbols', ...
        'adaptiveEqualizerDDPasses', ...
        'adaptiveEqualizerMaxTapNorm', ...
        'adaptiveEqualizerMinCMAConfidence', ...
        'adaptiveEqualizerRequireCMAConvergence', ...
        'adaptiveEqualizerQualityGuard', ...
        'adaptiveEqualizerMaxMSEDegradation', ...
        'adaptiveEqualizerMSEDegradationMargin', ...
        'adaptiveEqualizerScalarSideTapOnRatio', ...
        'adaptiveEqualizerDDWindowSymbols', ...
        'adaptiveEqualizerDDMinWindowAcceptance', ...
        'adaptiveEqualizerScalarDDPasses', ...
        'adaptiveEqualizerEnableFadeHold', ...
        'adaptiveEqualizerEnableQAMWindowHold', ...
        'adaptiveEqualizerAutoScalarForQAM', ...
        'enableAdaptiveFastEnvelopeTracker', ...
        'adaptiveFastEnvelopeEstimatorMode', ...
        'adaptiveFastEnvelopeTauSymbols', ...
        'adaptiveFastEnvelopeBlockSymbols', ...
        'adaptiveFastEnvelopeHopSymbols', ...
        'adaptiveFastEnvelopeMedianBlocks', ...
        'adaptiveFastEnvelopeTrimFraction', ...
        'adaptiveFastEnvelopeGainSlewDBPerSymbol', ...
        'adaptiveFastEnvelopeMinGainDB', ...
        'adaptiveFastEnvelopeMaxGainDB', ...
        'enableBlindReliabilityManager', ...
        'blindReliabilityWindowSymbols', ...
        'blindReliabilityAcquireSymbols', ...
        'blindReliabilityReferenceTauSymbols', ...
        'blindReliabilityFadeEnterDB', ...
        'blindReliabilityFadeExitDB', ...
        'blindReliabilityFadeEnterWindows', ...
        'blindReliabilityRecoverWindows', ...
        'blindReliabilityMaxInverseGainDB', ...
        'debugBlindReliabilityManager', ...
        'enableAdaptiveFastPhaseTracker', ...
        'enableQAMBlindPhaseSearch', ...
        'enableQAMBlindPhaseSearchForTPC', ...
        'QAMBlindPhaseSearch', ...
        'enableQAMPowerGainTracker', ...
        'QAMPowerGainTracker', ...
        'enableQAMPostBPSAdaptiveEqualizer', ...
        'enableAPSKQAMCarrierSync', ...
        'enableOQPSKHighRateTracking', ...
        'oqpskEnvelopeTauSymbols', ...
        'oqpskHighRatePhaseWindowSymbols', ...
        'enableUQPSKHighRateTracking', ...
        'enableUQPSKPostCarrierAdaptiveEqualizer', ...
        'enableUQPSKSecondPowerHighRatePhaseTracker', ...
        'enableUQPSKFourthPowerHighRatePhaseTracker', ...
        'enableUQPSKFFTCoarseCFO', ...
        'enableUQPSKDualBandwidthCarrierPLL', ...
        'uqpskCarrierAcquireLoopBW', ...
        'uqpskCarrierTrackLoopBW', ...
        'uqpskCarrierFadeThresholdDB', ...
        'uqpskCarrierLockErrorThreshold', ...
        'uqpskCarrierUnlockErrorThreshold', ...
        'uqpskCarrierLockSymbols', ...
        'uqpskCarrierUnlockSymbols', ...
        'uqpskCarrierMinAcquireSymbols', ...
        'uqpskCarrierErrorTauSymbols', ...
        'uqpskCarrierMaxFrequencyFraction', ...
        'uqpskEnvelopeTauSymbols', ...
        'uqpskHighRatePhaseWindowSymbols', ...
        'uqpskEnvelopeMinGainDB', ...
        'uqpskEnvelopeMaxGainDB'};
    for adaptiveIndex = 1:numel(adaptiveFields)
        adaptiveName = adaptiveFields{adaptiveIndex};
        if isfield(opts, adaptiveName) && ~isempty(opts.(adaptiveName))
            p.(adaptiveName) = opts.(adaptiveName);
        end
    end

    if isfield(opts, 'noisePSDdBmHz') && ~isempty(opts.noisePSDdBmHz)
        p.noisePSDdBmHz = double(opts.noisePSDdBmHz);
    end
    if isfield(opts, 'noiseBandwidthHz') && ~isempty(opts.noiseBandwidthHz)
        p.noiseBandwidthHz = double(opts.noiseBandwidthHz);
    end
    if isfield(opts, 'GMSKDetectionMode') && ~isempty(opts.GMSKDetectionMode)
        p.GMSKDetectionMode = char(opts.GMSKDetectionMode);
    end
    if isfield(opts, 'enableGMSKCoarseFrequencyCompensator') && ...
            ~isempty(opts.enableGMSKCoarseFrequencyCompensator)
        p.enableGMSKCoarseFrequencyCompensator = logical( ...
            opts.enableGMSKCoarseFrequencyCompensator);
    end
    gmskTrackerFields = { ...
        'enableGMSKResidualDopplerTracker', ...
        'gmskResidualWindowSymbols','gmskResidualHopSymbols', ...
        'gmskResidualMedianWindows','gmskResidualMinConfidenceDB', ...
        'gmskResidualMaxFrequencyFraction', ...
        'enableGMSKSecondOrderPLL','gmskPLLAcquireLoopBandwidth', ...
        'gmskPLLTrackLoopBandwidth','gmskPLLDetectorTauSymbols', ...
        'gmskPLLLockErrorThreshold','gmskPLLUnlockErrorThreshold', ...
        'gmskPLLLockSymbols','gmskPLLUnlockSymbols', ...
        'gmskPLLMinAcquireSymbols','gmskPLLFadeThresholdDB', ...
        'gmskPLLMaxFrequencyFraction'};
    for iGMSKTracker = 1:numel(gmskTrackerFields)
        trackerField = gmskTrackerFields{iGMSKTracker};
        p.(trackerField) = opts.(trackerField);
    end
    resetFields = {'gmskFrameResetASMMaxErrors', ...
        'gmskFrameResetASMMinGap', 'gmskFrameResetMaxSearchFrames', ...
        'gmskFrameResetMinSearchFrames'};
    for resetIndex = 1:numel(resetFields)
        resetName = resetFields{resetIndex};
        if isfield(opts, resetName) && ~isempty(opts.(resetName))
            p.(resetName) = double(opts.(resetName));
        end
    end

    if isfield(opts, 'debugCodedBoundary') && ~isempty(opts.debugCodedBoundary)
        p.debugCodedBoundary = logical(opts.debugCodedBoundary);
    end
    % Diagnostic-only switches must survive the sweep wrapper.  They are
    % intentionally absent from the defaults, so normal/release sweeps keep
    % exactly the same execution path and console volume.
    if isfield(opts, 'splitPathDebug') && ~isempty(opts.splitPathDebug)
        p.splitPathDebug = logical(opts.splitPathDebug);
    end
    if isfield(opts, 'debugTPC') && ~isempty(opts.debugTPC)
        p.debugTPC = logical(opts.debugTPC);
    end
    if isfield(opts, 'collectPredecoderStats') && ~isempty(opts.collectPredecoderStats)
        p.collectPredecoderStats = logical(opts.collectPredecoderStats);
    end
    if isfield(opts, 'predecoderMaxOffsetBits') && ~isempty(opts.predecoderMaxOffsetBits)
        p.predecoderMaxOffsetBits = double(opts.predecoderMaxOffsetBits);
    end
    if isfield(opts, 'debugFrameCheck') && ~isempty(opts.debugFrameCheck)
        p.debugFrameCheck = logical(opts.debugFrameCheck);
    end
    if isfield(opts, 'debugFrameCheckCount') && ~isempty(opts.debugFrameCheckCount)
        p.debugFrameCheckCount = double(opts.debugFrameCheckCount);
    end
    if isfield(opts, 'debugAllPerFrameBER') && ~isempty(opts.debugAllPerFrameBER)
        p.debugAllPerFrameBER = logical(opts.debugAllPerFrameBER);
    end
    if isfield(opts, 'debugPerFrameBERCount') && ~isempty(opts.debugPerFrameBERCount)
        p.debugPerFrameBERCount = double(opts.debugPerFrameBERCount);
    end
    if isfield(opts, 'debugPerFrameBERFormat') && ~isempty(opts.debugPerFrameBERFormat)
        p.debugPerFrameBERFormat = char(opts.debugPerFrameBERFormat);
    end
    if isfield(opts, 'debugPerFrameBERSummary') && ~isempty(opts.debugPerFrameBERSummary)
        p.debugPerFrameBERSummary = logical(opts.debugPerFrameBERSummary);
    end
    if isfield(opts, 'debugPerFrameBERNonzeroCount') && ~isempty(opts.debugPerFrameBERNonzeroCount)
        p.debugPerFrameBERNonzeroCount = double(opts.debugPerFrameBERNonzeroCount);
    end
    if isfield(opts, 'debugGMSK') && ~isempty(opts.debugGMSK)
        p.debugGMSK = logical(opts.debugGMSK);
    end
    if isfield(opts, 'debugGMSKResidualTracker') && ~isempty(opts.debugGMSKResidualTracker)
        p.debugGMSKResidualTracker = logical(opts.debugGMSKResidualTracker);
    end
    if isfield(opts, 'debugGMSKSecondOrderPLL') && ~isempty(opts.debugGMSKSecondOrderPLL)
        p.debugGMSKSecondOrderPLL = logical(opts.debugGMSKSecondOrderPLL);
    end
    if isfield(opts, 'gmskResidualDebugMaxWindows') && ~isempty(opts.gmskResidualDebugMaxWindows)
        p.gmskResidualDebugMaxWindows = double(opts.gmskResidualDebugMaxWindows);
    end
    if isfield(opts, 'debugMSK') && ~isempty(opts.debugMSK)
        p.debugMSK = logical(opts.debugMSK);
    end
    if isfield(opts, 'debugUQPSK') && ~isempty(opts.debugUQPSK)
        p.debugUQPSK = logical(opts.debugUQPSK);
    end
    if isfield(opts, 'debugASMPhase') && ~isempty(opts.debugASMPhase)
        p.debugASMPhase = logical(opts.debugASMPhase);
    end
    asmPhaseFields = { ...
        'enableASMFramePhaseCorrection', ...
        'asmFramePhaseCorrectionMaxError', ...
        'asmFramePhaseCorrectionMinGap', ...
        'asmFramePhaseCorrectionMinReliableFraction', ...
        'debugASMPhaseTimelineFrames'};
    for asmPhaseIndex = 1:numel(asmPhaseFields)
        asmPhaseName = asmPhaseFields{asmPhaseIndex};
        if isfield(opts, asmPhaseName) && ~isempty(opts.(asmPhaseName))
            p.(asmPhaseName) = opts.(asmPhaseName);
        end
    end
    if isfield(opts, 'debugEqualizerStats') && ~isempty(opts.debugEqualizerStats)
        p.debugEqualizerStats = logical(opts.debugEqualizerStats);
    end
    if isfield(opts, 'debugAdaptiveEqualizer') && ~isempty(opts.debugAdaptiveEqualizer)
        p.debugAdaptiveEqualizer = logical(opts.debugAdaptiveEqualizer);
    end
    if isfield(opts, 'debugSynchronizationChain') && ...
            ~isempty(opts.debugSynchronizationChain)
        p.debugSynchronizationChain = logical(opts.debugSynchronizationChain);
    end
    if isfield(opts, 'debugSyncSegmentCount') && ...
            ~isempty(opts.debugSyncSegmentCount)
        p.debugSyncSegmentCount = double(opts.debugSyncSegmentCount);
    end
    if isfield(opts, 'debugCarrierRecovery') && ...
            ~isempty(opts.debugCarrierRecovery)
        p.debugCarrierRecovery = logical(opts.debugCarrierRecovery);
    end
    if isfield(opts, 'debugHFrameStats') && ~isempty(opts.debugHFrameStats)
        p.debugHFrameStats = logical(opts.debugHFrameStats);
    end
    if isfield(opts, 'debugHFrameStatsStart') && ~isempty(opts.debugHFrameStatsStart)
        p.debugHFrameStatsStart = double(opts.debugHFrameStatsStart);
    end
    if isfield(opts, 'debugHFrameStatsCount') && ~isempty(opts.debugHFrameStatsCount)
        p.debugHFrameStatsCount = double(opts.debugHFrameStatsCount);
    end
    if isfield(opts, 'debugCodedFrameSyncPrintLimit') && ~isempty(opts.debugCodedFrameSyncPrintLimit)
        p.debugCodedFrameSyncPrintLimit = double(opts.debugCodedFrameSyncPrintLimit);
    end
    if isfield(opts, 'debugResetCodedFrameSyncPerSplitCandidate') && ...
            ~isempty(opts.debugResetCodedFrameSyncPerSplitCandidate)
        p.debugResetCodedFrameSyncPerSplitCandidate = ...
            logical(opts.debugResetCodedFrameSyncPerSplitCandidate);
    end
    frameSyncFields = { ...
        'FrameSyncBitSlipTolerance', ...
        'FrameSyncASMErrorThreshold', ...
        'FrameSyncLockThreshold', ...
        'FrameSyncUnlockThreshold'};
    for frameSyncIndex = 1:numel(frameSyncFields)
        frameSyncField = frameSyncFields{frameSyncIndex};
        if isfield(opts, frameSyncField) && ~isempty(opts.(frameSyncField))
            p.(frameSyncField) = double(opts.(frameSyncField));
        end
    end
    splitConvSyncFields = { ...
        'enableSplitConvolutionalRailPolaritySearch', ...
        'SplitConvolutionalFrameSyncASMErrorThreshold'};
    for splitConvIndex = 1:numel(splitConvSyncFields)
        splitConvField = splitConvSyncFields{splitConvIndex};
        if isfield(opts, splitConvField) && ~isempty(opts.(splitConvField))
            p.(splitConvField) = opts.(splitConvField);
        end
    end
    if isfield(opts, 'enableCodedPhaseSearch') && ~isempty(opts.enableCodedPhaseSearch)
        p.enableCodedPhaseSearch = logical(opts.enableCodedPhaseSearch);
    end
    if isfield(opts, 'phaseResolveFallback') && ~isempty(opts.phaseResolveFallback)
        p.phaseResolveFallback = logical(opts.phaseResolveFallback);
    end
    if isfield(opts, 'phaseResolveMode') && ~isempty(opts.phaseResolveMode)
        p.phaseResolveMode = char(opts.phaseResolveMode);
    end
end

function p = localApplyModulationParams(p, modType, opts)
    if contains(upper(modType), 'APSK')
        p.APSKReceiverMode = char(opts.APSKReceiverMode);
        p.enablePilotlessAPSKComplexGainTracker = logical( ...
            opts.enablePilotlessAPSKComplexGainTracker);
        p.PilotlessAPSKCarrierRecovery = ...
            opts.PilotlessAPSKCarrierRecovery;
        p.PilotlessAPSKComplexGainTracker = ...
            opts.PilotlessAPSKComplexGainTracker;
        p.enablePilotlessAPSKPostFrontEndAdaptiveEqualizer = logical( ...
            opts.enablePilotlessAPSKPostFrontEndAdaptiveEqualizer);
        p.debugPilotlessAPSK = logical(opts.debugPilotlessAPSK);
        p.timingLoopBandwidth = opts.apskTimingLoopBandwidth;
        p.enableAdaptiveFastPhaseTracker = logical( ...
            opts.enableAdaptiveAPSKFastPhaseTracker);
        p.enableAPSKCoarseFrequencyCompensator = logical( ...
            opts.enableAPSKCoarseFrequencyCompensator);
        p.WaveformMode = char(opts.WaveformMode);
        p.HasTMAPSKPilots = logical(opts.useTMAPSKPilots);
        p.TMAPSKPilotInterval = opts.TMAPSKPilotInterval;
        p.TMAPSKPilotLength = opts.TMAPSKPilotLength;
        p.TMAPSKPilotPreambleLength = opts.TMAPSKPilotPreambleLength;
        p.TMAPSKPilotCorrectionMode = opts.TMAPSKPilotCorrectionMode;
        p.TMAPSKPilotPhaseSmoothWindow = opts.TMAPSKPilotPhaseSmoothWindow;
        p.TMAPSKPilotMMSERegularization = opts.TMAPSKPilotMMSERegularization;
        p.TMAPSKPilotMaxGainDB = opts.TMAPSKPilotMaxGainDB;
        p.TMAPSKPilotFadeThresholdDB = opts.TMAPSKPilotFadeThresholdDB;
        p.TMAPSKPilotFadeHold = logical(opts.TMAPSKPilotFadeHold);
        p.enableAPSKPilotFadeEqualizerHold = logical( ...
            opts.enableAPSKPilotFadeEqualizerHold);
        if ~isempty(opts.facmWarmupFrames)
            p.facmWarmupFrames = double(opts.facmWarmupFrames);
        end
        if ~isempty(opts.facmBERFrames)
            p.facmBERFrames = double(opts.facmBERFrames);
        end
        if ~isempty(opts.facmNumIterations)
            p.facmNumIterations = double(opts.facmNumIterations);
        end
        if isfield(opts, 'debugFACM') && ~isempty(opts.debugFACM)
            p.debugFACM = logical(opts.debugFACM);
        end
        if ~isempty(opts.enableFACMEqualizer)
            p.enableFACMEqualizer = logical(opts.enableFACMEqualizer);
        end
        if ~isempty(opts.facmEqualizerMode)
            p.facmEqualizerMode = char(opts.facmEqualizerMode);
        end
        if ~isempty(opts.facmEqualizerReg)
            p.facmEqualizerReg = double(opts.facmEqualizerReg);
        end
        if ~isempty(opts.facmEqualizerTaps)
            p.facmEqualizerTaps = double(opts.facmEqualizerTaps);
        end
    end

    if strcmpi(modType, 'GMSK')
        p.BandwidthTimeProduct = opts.gmskBT;
    elseif strcmpi(modType, 'MSK')
        p.enableCPMCoarseFrequencyCompensator = logical( ...
            opts.enableCPMCoarseFrequencyCompensator);
    end
end

function p = localApplyCodingParams(p, code)
    clearFields = {'ConvolutionalCodeRate','CodeRate','NumBitsInInformationBlock', ...
        'IsLDPCOnSMTF','LDPCCodeblockSize','TPCCodeRate','TPCBlocksPerTF'};
    for i = 1:numel(clearFields)
        if isfield(p, clearFields{i})
            p = rmfield(p, clearFields{i});
        end
    end

    p.channelCoding = code.ChannelCoding;
    p.NumBytesInTransferFrame = code.NumBytesInTransferFrame;

    extraNames = fieldnames(code.Extra);
    for i = 1:numel(extraNames)
        p.(extraNames{i}) = code.Extra.(extraNames{i});
    end
end

function p = localApplyChannelParams(p, ch, opts)
    p.enableHChannel = ch.EnableHChannel;
    p.enableEqualizer = ch.EnableEqualizer;
    p.normalizeHChannel = ch.NormalizeHChannel;
    p.normalizeEqualizerOutput = ch.NormalizeEqualizerOutput;

    if ch.EnableHChannel
        p.HMode = 'h_matrix_file';

        if isfield(ch, 'ChannelFilePath') && ~isempty(ch.ChannelFilePath)
            p.channelFilePath = ch.ChannelFilePath;
        else
            p.channelFilePath = opts.channelFilePath;
        end

        p.channelInterpolationMethod = opts.channelInterpolationMethod;
        if isfield(opts, 'channelOutOfRangeMode') && ~isempty(opts.channelOutOfRangeMode)
            p.channelOutOfRangeMode = char(opts.channelOutOfRangeMode);
        end
        p.interpolateChannelDelays = opts.interpolateChannelDelays;

        % H-component diagnostics must reach run_ccsds_tm_evaluation.
        % Without this forwarding, setting these fields on the sweep options
        % is silently ignored and normal H is tested in every run.
        hDiagnosticFields = {'debugHMatrixResponseMode', 'applyPMode'};
        for diagnosticIndex = 1:numel(hDiagnosticFields)
            diagnosticName = hDiagnosticFields{diagnosticIndex};
            if isfield(opts, diagnosticName) && ~isempty(opts.(diagnosticName))
                p.(diagnosticName) = opts.(diagnosticName);
            end
        end
    end

    if ch.EnableEqualizer
        p.equalizerMode = opts.equalizerMode;
        if ~isempty(opts.equalizerReg)
            p.equalizerReg = opts.equalizerReg;
        end
    end
end

function cases = localBuildChannelCases(opts)
    cases = {};

    if opts.includeNoHBaseline
        cases{end+1} = struct( ...
            'Name', 'NoH_baseline', ...
            'EnableHChannel', false, ...
            'EnableEqualizer', false, ...
            'NormalizeHChannel', false, ...
            'NormalizeEqualizerOutput', false, ...
            'ChannelFilePath', ''); %#ok<AGROW>
    end

    if isfield(opts, 'includeNoHEqualizedBaseline') && ...
            logical(opts.includeNoHEqualizedBaseline)
        cases{end+1} = struct( ...
            'Name', 'NoH_EQ_baseline', ...
            'EnableHChannel', false, ...
            'EnableEqualizer', true, ...
            'NormalizeHChannel', false, ...
            'NormalizeEqualizerOutput', opts.normalizeEqualizerOutput, ...
            'ChannelFilePath', ''); %#ok<AGROW>
    end

    % 这里新增：支持多个 H 文件
    if isfield(opts, 'hModelCases') && ~isempty(opts.hModelCases)
        hModelCases = opts.hModelCases;
    else
        hModelCases = { ...
            'H_EQ_rawGain', opts.channelFilePath};
    end

    if opts.includeHEqualized
        for i = 1:size(hModelCases, 1)
            hLabel = char(hModelCases{i, 1});
            hFile  = char(hModelCases{i, 2});

            cases{end+1} = struct( ...
                'Name', ['H_EQ_rawGain_' hLabel], ...
                'EnableHChannel', true, ...
                'EnableEqualizer', true, ...
                'NormalizeHChannel', false, ...
                'NormalizeEqualizerOutput', opts.normalizeEqualizerOutput, ...
                'ChannelFilePath', hFile); %#ok<AGROW>
        end
    end

    if opts.includeNormHScenario
        for i = 1:size(hModelCases, 1)
            hLabel = char(hModelCases{i, 1});
            hFile  = char(hModelCases{i, 2});

            cases{end+1} = struct( ...
                'Name', ['H_EQ_normH_' hLabel], ...
                'EnableHChannel', true, ...
                'EnableEqualizer', true, ...
                'NormalizeHChannel', true, ...
                'NormalizeEqualizerOutput', opts.normalizeEqualizerOutput, ...
                'ChannelFilePath', hFile); %#ok<AGROW>
        end
    end

    if opts.includeNoEqualizerScenario
        for i = 1:size(hModelCases, 1)
            hLabel = char(hModelCases{i, 1});
            hFile  = char(hModelCases{i, 2});

            cases{end+1} = struct( ...
                'Name', ['H_noEQ_rawGain_' hLabel], ...
                'EnableHChannel', true, ...
                'EnableEqualizer', false, ...
                'NormalizeHChannel', false, ...
                'NormalizeEqualizerOutput', false, ...
                'ChannelFilePath', hFile); %#ok<AGROW>
        end
    end
end

function cases = localBuildCodingCases(opts)
    cases = {};

    if opts.includeUncoded
        cases{end+1} = localCodingCase('none', 'none', ...
            localMaybeOverrideTransferFrameBytes(1115, opts), struct()); %#ok<AGROW>
    end

    if opts.includeRS
        extra = struct( ...
            'RSMessageLength', 223, ...
            'RSInterleavingDepth', 1, ...
            'IsRSMessageShortened', false);
        cases{end+1} = localCodingCase('RS', '223/255', ...
            localMaybeOverrideTransferFrameBytes(1115, opts), extra); %#ok<AGROW>
    end

    if opts.includeConvolutional
        for i = 1:numel(opts.convRates)
            rate = char(opts.convRates{i});
            extra = struct('ConvolutionalCodeRate', rate);
            cases{end+1} = localCodingCase('convolutional', rate, ...
                localMaybeOverrideTransferFrameBytes(localConvTransferFrameBytes(rate), opts), extra); %#ok<AGROW>
        end
    end

    if opts.includeLDPC
        for i = 1:numel(opts.ldpcRates)
            rate = char(opts.ldpcRates{i});
            if strcmp(rate, '7/8')
                informationBits = 7136;
            else
                informationBits = 1024;
            end
            extra = struct( ...
                'CodeRate', rate, ...
                'NumBitsInInformationBlock', informationBits, ...
                'IsLDPCOnSMTF', false);
            cases{end+1} = localCodingCase('LDPC', rate, 1115, extra); %#ok<AGROW>
        end
    end

    if opts.includeTurbo
        for i = 1:numel(opts.turboRates)
            rate = char(opts.turboRates{i});
            extra = struct( ...
                'CodeRate', rate, ...
                'NumBitsInInformationBlock', 1784);
            cases{end+1} = localCodingCase('Turbo', rate, 1115, extra); %#ok<AGROW>
        end
    end

    if opts.includeTPC
        for i = 1:numel(opts.tpcCases)
            tpc = opts.tpcCases{i};
            tfBytes = localTPCTransferFrameBytes(tpc.TPCCodeRate, tpc.TPCBlocksPerTF);
            if ~isfinite(tfBytes) || tfBytes > 2048
                fprintf(2, '[skip] TPC %s, blocks %d gives invalid TF bytes %.0f.\n', ...
                    char(tpc.TPCCodeRate), double(tpc.TPCBlocksPerTF), tfBytes);
                continue;
            end
            label = sprintf('%s_x%d', char(tpc.TPCCodeRate), double(tpc.TPCBlocksPerTF));
            extra = struct( ...
                'TPCCodeRate', char(tpc.TPCCodeRate), ...
                'TPCBlocksPerTF', double(tpc.TPCBlocksPerTF));
            cases{end+1} = localCodingCase('TPC', label, tfBytes, extra); %#ok<AGROW>
        end
    end
end

function tfBytes = localMaybeOverrideTransferFrameBytes(defaultBytes, opts)
    tfBytes = double(defaultBytes);
    override = [];
    if isfield(opts, 'forceNumBytesInTransferFrame') && ~isempty(opts.forceNumBytesInTransferFrame)
        override = opts.forceNumBytesInTransferFrame;
    elseif isfield(opts, 'NumBytesInTransferFrame') && ~isempty(opts.NumBytesInTransferFrame) && ...
            double(opts.NumBytesInTransferFrame) ~= 1115
        override = opts.NumBytesInTransferFrame;
    end
    if ~isempty(override)
        tfBytes = round(double(override));
    end
    if ~isfinite(tfBytes) || tfBytes < 8
        error('sweep_h_channel_short_frames:InvalidTransferFrameBytes', ...
            'NumBytesInTransferFrame override must be at least 8 bytes.');
    end
end

function c = localCodingCase(channelCoding, rateLabel, numBytes, extra)
    c = struct( ...
        'ChannelCoding', char(channelCoding), ...
        'RateLabel', char(rateLabel), ...
        'NumBytesInTransferFrame', double(numBytes), ...
        'Extra', extra);
end

function tfBytes = localConvTransferFrameBytes(rate)
    switch char(rate)
        case '5/6'
            tfBytes = 1116;
        case '7/8'
            tfBytes = 1123;
        otherwise
            tfBytes = 1115;
    end
end

function tfBytes = localTPCTransferFrameBytes(rateName, blocksPerTF)
    payloadBits = localTPCPayloadBits(rateName) * max(1, round(double(blocksPerTF)));
    if mod(payloadBits, 8) == 0
        tfBytes = payloadBits / 8;
    else
        tfBytes = NaN;
    end
end

function bits = localTPCPayloadBits(rateName)
    switch char(rateName)
        case '1/2'
            side = 32;
        case '2/3'
            side = 52;
        case 'native'
            side = 57;
        otherwise
            val = str2double(char(rateName));
            if isfinite(val) && val > 0 && val <= 57 && mod(val, 1) == 0
                side = val;
            else
                error('sweep_h_channel_short_frames:InvalidTPCCodeRate', ...
                    'Unsupported TPCCodeRate="%s".', char(rateName));
            end
    end
    bits = side * side;
end

function tf = localIsCaseCompatible(modType, code, opts)
    tf = true;

    if strcmpi(modType, '4D-8PSK-TCM') && ~strcmpi(code.ChannelCoding, 'none')
        tf = false;
        return;
    end

    isAPSK = contains(upper(string(modType)), 'APSK');
    if isAPSK && strcmpi(char(opts.WaveformMode), 'FACM') && ...
            ~strcmpi(code.ChannelCoding, 'none')
        tf = false;
        return;
    end
end

function row = localMakeRow(idx, ch, modType, code, p, r, ok, status, err, elapsed)
    hNormGain = NaN;
    hMeanCoeff = NaN;
    hOutOfRangeMode = "";
    hSourceDuration_s = NaN;
    hWaveformDuration_s = NaN;
    hExceedsDuration = false;
    hResponseMode = "";
    if isfield(r, 'channelMeta') && isstruct(r.channelMeta)
        hNormGain = localField(r.channelMeta, 'NormalizationGain_dB', NaN);
        hMeanCoeff = localField(r.channelMeta, 'MeanCoeffMagnitude', NaN);
        hOutOfRangeMode = string(localStructChar(r.channelMeta, 'OutOfRangeMode', ""));
        hSourceDuration_s = localField(r.channelMeta, 'ChannelSourceDuration_s', NaN);
        hWaveformDuration_s = localField(r.channelMeta, 'WaveformDuration_s', NaN);
        hExceedsDuration = logical(localField(r.channelMeta, 'ExceedsChannelDuration', false));
        hResponseMode = string(localStructChar(r.channelMeta, 'DebugResponseMode', ""));
    end

    infoBits = NaN;
    if isfield(p, 'NumBitsInInformationBlock')
        infoBits = double(p.NumBitsInInformationBlock);
    end

    ldpcOnSMTF = false;
    if isfield(p, 'IsLDPCOnSMTF')
        ldpcOnSMTF = logical(p.IsLDPCOnSMTF);
    end

    tpcBlocks = NaN;
    if isfield(p, 'TPCBlocksPerTF')
        tpcBlocks = double(p.TPCBlocksPerTF);
    end
    frameDuration_s = localFrameDurationSeconds(modType, p);
    countedFrames = localField(r, 'CountedFrames', NaN);
    matchedFrames = localField(r, 'MatchedFrames', NaN);

    row = { ...
        double(idx), ...
        string(ch.Name), ...
        string(modType), ...
        string(code.ChannelCoding), ...
        string(code.RateLabel), ...
        logical(localStructNumeric(p, 'RandomizerEnabled', 0)), ...
        string(localStructChar(p, 'RandomizerFECPosition', 'afterEncoding')), ...
        string(localStructChar(p, 'DataPathMode', 'single')), ...
        string(localStructChar(r, 'TMDataSource', ...
            localStructChar(p, 'TMDataSource', 'random'))), ...
        string(localStructChar(r, 'TMDataSourceI', ...
            localStructChar(p, 'TMDataSourceI', ''))), ...
        string(localStructChar(r, 'TMDataSourceQ', ...
            localStructChar(p, 'TMDataSourceQ', ''))), ...
        string(localStructChar(r, 'ConvolutionalG1G2Mode', ...
            localStructChar(p, 'ConvolutionalG1G2Mode', 'auto-ccsds'))), ...
        localStructNumeric(p, 'cfo', 0), ...
        localField(r, 'CarrierCaptureRangeConfigured_Hz', ...
            localStructNumeric(p, 'carrierCaptureRangeHz', NaN)), ...
        localStructNumeric(p, 'phaseOffset', 0), ...
        localStructNumeric(p, 'delay', 0), ...
        double(p.NumBytesInTransferFrame), ...
        infoBits, ...
        ldpcOnSMTF, ...
        tpcBlocks, ...
        logical(ch.EnableHChannel), ...
        logical(ch.EnableEqualizer), ...
        logical(ch.NormalizeHChannel), ...
        logical(ch.NormalizeEqualizerOutput), ...
        localField(r, 'BER', NaN), ...
        100 * localField(r, 'LockRate', NaN), ...
        localField(r, 'FER', NaN), ...
        countedFrames, ...
        matchedFrames, ...
        frameDuration_s, ...
        matchedFrames * frameDuration_s, ...
        countedFrames * frameDuration_s, ...
        localField(r, 'EVM_post_pct', NaN), ...
        localField(r, 'EVMRadial_pct', NaN), ...
        localField(r, 'EVMTangential_pct', NaN), ...
        localField(r, 'ResidualPhaseRMS_deg', NaN), ...
        localField(r, 'ResidualRadiusRMS_dB', NaN), ...
        localField(r, 'MER_dB', NaN), ...
        localField(r, 'SNR_est_dB', NaN), ...
        localField(r, 'ResidualCFO_Hz', NaN), ...
        localField(r, 'HGain_dB', NaN), ...
        hNormGain, ...
        hMeanCoeff, ...
        hOutOfRangeMode, ...
        hSourceDuration_s, ...
        hWaveformDuration_s, ...
        hExceedsDuration, ...
        hResponseMode, ...
        logical(localStructNumeric(p, 'applyPMode', 1)), ...
        string(localStructChar(p, 'noisePlacement', localStructChar(r, 'NoisePlacement', 'afterChannel'))), ...
        string(localStructChar(r, 'NoiseMode', localStructChar(p, 'noiseMode', 'psd'))), ...
        localField(r, 'NoisePSD_dBmHz', localStructNumeric(p, 'noisePSDdBmHz', NaN)), ...
        localField(r, 'NoiseBandwidthHz', localStructNumeric(p, 'noiseBandwidthHz', NaN)), ...
        localField(r, 'NoisePower_dBm', NaN), ...
        localField(r, 'NoiseEquivalentSNR_dB', NaN), ...
        localField(r, 'ConverterChainEnabled', false), ...
        localField(r, 'BasebandIFLevel_dBm', NaN), ...
        localField(r, 'UpconverterNetGain_dB', NaN), ...
        localField(r, 'UpconverterAttenuation_dB', NaN), ...
        localField(r, 'UpconverterOutputLevel_dBm', NaN), ...
        localField(r, 'UpconverterCompressionRisk', false), ...
        localField(r, 'HAppliedGain_dB', NaN), ...
        localField(r, 'DownconverterInputLevel_dBm', NaN), ...
        localField(r, 'DownconverterNetGain_dB', NaN), ...
        localField(r, 'DownconverterAttenuation_dB', NaN), ...
        localField(r, 'DownconverterAutoAttenuation', false), ...
        localField(r, 'DownconverterOutputLevel_dBm', NaN), ...
        localField(r, 'DownconverterInputWithinTypicalRange', false), ...
        localField(r, 'DownconverterCompressionRisk', false), ...
        localField(r, 'ADCEquivalentEnabled', false), ...
        localField(r, 'ADCRMSBackoff_dB', NaN), ...
        100*localField(r, 'ADCClipFraction', NaN), ...
        string(localStructChar(p, 'equalizerMode', '')), ...
        string(localStructChar(r, 'FastEnvelopeEstimatorMode', ...
            localStructChar(p, 'adaptiveFastEnvelopeEstimatorMode', 'auto'))), ...
        localField(r, 'FastEnvelopeTauSymbols', ...
            localStructNumeric(p, 'adaptiveFastEnvelopeTauSymbols', NaN)), ...
        localField(r, 'FastEnvelopeBlockSymbols', ...
            localStructNumeric(p, 'adaptiveFastEnvelopeBlockSymbols', NaN)), ...
        localField(r, 'FastEnvelopeHopSymbols', ...
            localStructNumeric(p, 'adaptiveFastEnvelopeHopSymbols', NaN)), ...
        localField(r, 'FastEnvelopeGainSlewDBPerSymbol', ...
            localStructNumeric(p, ...
            'adaptiveFastEnvelopeGainSlewDBPerSymbol', NaN)), ...
        localStructNumeric(p, 'adaptiveFastEnvelopeMinGainDB', -40), ...
        localStructNumeric(p, 'adaptiveFastEnvelopeMaxGainDB', 100), ...
        localField(r, 'FastEnvelopeGainMin_dB', NaN), ...
        localField(r, 'FastEnvelopeGainMax_dB', NaN), ...
        localField(r, 'BlindReliabilityApplied', false), ...
        string(localStructChar(r, 'BlindReliabilityFinalState','TRACK')), ...
        100*localField(r, 'BlindReliabilityHoldFraction', NaN), ...
        localField(r, 'BlindReliabilityHoldEvents', NaN), ...
        localField(r, 'BlindReliabilityRecoverEvents', NaN), ...
        localField(r, 'BlindReliabilityMinRelativePower_dB', NaN), ...
        localField(r, 'BlindReliabilityMaxInverseGain_dB', NaN), ...
        localStructNumeric(p, 'adaptiveEqualizerDDWindowSymbols', NaN), ...
        localStructNumeric(p, 'adaptiveEqualizerDDMinWindowAcceptance', NaN), ...
        localField(r, 'AdaptiveEqualizerDDPasses', NaN), ...
        localStructNumeric(p, 'adaptiveEqualizerScalarDDPasses', NaN), ...
        localField(r, 'AdaptiveEqualizerDecisionGate', NaN), ...
        localField(r, 'AdaptiveEqualizerCMASwitchMSE', NaN), ...
        localField(r, 'AdaptiveEqualizerCMAMSE', NaN), ...
        100*localField(r, 'AdaptiveEqualizerAcceptanceRate', NaN), ...
        localField(r, 'AdaptiveEqualizerDDMSE', NaN), ...
        localField(r, 'ASMTrainingEqualizerASMCount', NaN), ...
        localField(r, 'ASMTrainingEqualizerUpdates', NaN), ...
        localField(r, 'ASMTrainingEqualizerMedianScoreBefore', NaN), ...
        localField(r, 'ASMTrainingEqualizerMedianScoreAfter', NaN), ...
        localField(r, 'PredecoderBER', NaN), ...
        localField(r, 'PredecoderOffset', NaN), ...
        localField(r, 'PredecoderPolarity', NaN), ...
        localField(r, 'PredecoderTxFrameOffset', NaN), ...
        localField(r, 'PredecoderASMAligned', false), ...
        localField(r, 'PredecoderBitErrors', NaN), ...
        localField(r, 'PredecoderBitsCompared', NaN), ...
        localField(r, 'PredecoderSteadyBER', NaN), ...
        localField(r, 'PredecoderSteadyBitErrors', NaN), ...
        localField(r, 'PredecoderSteadyBitsCompared', NaN), ...
        localField(r, 'PredecoderFramesCompared', NaN), ...
        localField(r, 'PredecoderFrameBERP95', NaN), ...
        localField(r, 'PredecoderFrameBERMax', NaN), ...
        localField(r, 'ASMFramePhaseCorrectionEnabled', false), ...
        localField(r, 'ASMFramePhaseCorrectionApplied', false), ...
        localField(r, 'ASMFramePhaseCorrectionFrames', NaN), ...
        localField(r, 'ASMFramePhaseCorrectionReliableFrames', NaN), ...
        localField(r, 'ASMFramePhaseCycleSlipsBefore', NaN), ...
        localField(r, 'ASMFramePhaseCycleSlipsAfter', NaN), ...
        localField(r, 'AdaptiveEqualizerDDWindowCount', NaN), ...
        localField(r, 'AdaptiveEqualizerDDGoodWindows', NaN), ...
        localField(r, 'AdaptiveEqualizerDDHoldWindows', NaN), ...
        localField(r, 'AdaptiveEqualizerDDFadeHoldWindows', NaN), ...
        localField(r, 'AdaptiveEqualizerDDFadeEnterEvents', NaN), ...
        localField(r, 'AdaptiveEqualizerDDFadeRecoverEvents', NaN), ...
        localField(r, 'TMAPSKPilotDataFadeSymbols', NaN), ...
        100*localField(r, 'TMAPSKPilotDataFadeFraction', NaN), ...
        localField(r, ...
            'AdaptiveEqualizerExternalFadeMaskProvided', false), ...
        localField(r, ...
            'AdaptiveEqualizerExternalFadeMaskLengthMatched', false), ...
        localField(r, ...
            'AdaptiveEqualizerExternalFadeMaskInputLength', NaN), ...
        localField(r, ...
            'AdaptiveEqualizerExternalFadeInputSymbols', NaN), ...
        localField(r, ...
            'AdaptiveEqualizerExternalFadeExpandedSymbols', NaN), ...
        localField(r, ...
            'AdaptiveEqualizerDDExternalFadeHoldWindows', NaN), ...
        localField(r, ...
            'AdaptiveEqualizerDDExternalFadeHoldSymbols', NaN), ...
        localField(r, 'HighRatePhaseTrackingApplied', false), ...
        localField(r, 'HighRatePhaseWindowSymbols', NaN), ...
        localField(r, 'HighRatePhaseMeanConfidence', NaN), ...
        localField(r, 'HighRatePhaseHoldSamples', NaN), ...
        localField(r, 'UQPSKPostCarrierEQEnabled', true), ...
        string(localStructChar(r, 'APSKReceiverMode', ...
            localStructChar(p, 'APSKReceiverMode', 'pilotless'))), ...
        localField(r, 'QAMBlindPhaseSearchApplied', false), ...
        100*localField(r, 'QAMBlindPhaseSearchReliableRate', NaN), ...
        localField(r, 'QAMBlindPhaseSearchMedianMetric', NaN), ...
        localField(r, 'QAMBlindPhaseSearchFinalCorrection_deg', NaN), ...
        localField(r, 'QAMBlindPhaseSearchFadeHoldBlocks', NaN), ...
        localField(r, 'QAMBlindPhaseSearchFadeEvents', NaN), ...
        localField(r, 'QAMBlindPhaseSearchFadeRecoveries', NaN), ...
        localField(r, 'QAMBlindPhaseSearchReacquisitions', NaN), ...
        localField(r, ...
            'QAMBlindPhaseSearchInitialFrequencyRadPerSymbol', NaN), ...
        localField(r, 'QAMPowerGainApplied', false), ...
        100*localField(r, 'QAMPowerGainAcceptanceRate', NaN), ...
        localField(r, 'QAMPowerGainRegularization', NaN), ...
        localField(r, 'QAMPowerGainMaxInverseGainDB', NaN), ...
        localField(r, 'QAMPowerGainInverseMaxObserved_dB', NaN), ...
        localField(r, 'PilotlessAPSKApplied', false), ...
        localField(r, 'PilotlessAPSKCoarsePowerOrder', NaN), ...
        localField(r, 'PilotlessAPSKFourthPowerCFO_Hz', NaN), ...
        localField(r, 'PilotlessAPSKFourthPowerConfidence_dB', NaN), ...
        localField(r, 'PilotlessAPSKNDAResidualCFO_Hz', NaN), ...
        localField(r, 'PilotlessAPSKNDAResidualCFOApplied', false), ...
        localField(r, 'PilotlessAPSKMthPowerPhaseTrackerApplied', false), ...
        localField(r, 'PilotlessAPSKMthPowerPhaseFinalCorrection_deg', NaN), ...
        localField(r, 'PilotlessAPSKMthPowerPhaseMedianConfidence', NaN), ...
        localField(r, 'PilotlessAPSKBlindPhaseSearchApplied', false), ...
        100*localField(r, 'PilotlessAPSKBlindPhaseSearchReliableRate', NaN), ...
        localField(r, 'PilotlessAPSKBlindPhaseSearchMedianMetric', NaN), ...
        localField(r, 'PilotlessAPSKBlindPhaseSearchFinalCorrection_deg', NaN), ...
        localField(r, 'PilotlessAPSKPreDDGainApplied', false), ...
        100*localField(r, 'PilotlessAPSKPreDDGainAcceptanceRate', NaN), ...
        100*localField(r, 'PilotlessAPSKPreDDGainHoldFraction', NaN), ...
        100*localField(r, 'PilotlessAPSKPreDDGainFadeFraction', NaN), ...
        localField(r, 'PilotlessAPSKPreDDGainFinalMagnitude_dB', NaN), ...
        localField(r, 'PilotlessAPSKRingNormalizerApplied', false), ...
        string(localStructChar(r, 'PilotlessAPSKRingEstimatorMode','off')), ...
        100*localField(r, 'PilotlessAPSKRingAcceptanceRate', NaN), ...
        100*localField(r, 'PilotlessAPSKRingHoldFraction', NaN), ...
        100*localField(r, 'PilotlessAPSKRingFadeFraction', NaN), ...
        localField(r, 'PilotlessAPSKRingFinalAmplitude_dB', NaN), ...
        100*localField(r, 'PilotlessAPSKCarrierAcceptanceRate', NaN), ...
        100*localField(r, 'PilotlessAPSKCarrierHoldFraction', NaN), ...
        localField(r, 'PilotlessAPSKCarrierPhaseErrorRMS_deg', NaN), ...
        localField(r, 'PilotlessAPSKResidualFrequency_Hz', NaN), ...
        100*localField(r, 'PilotlessAPSKGainAcceptanceRate', NaN), ...
        localField(r, 'PilotlessAPSKGainRegularization', NaN), ...
        localField(r, 'PilotlessAPSKGainMaxInverseGainDB', NaN), ...
        localField(r, 'PilotlessAPSKGainInverseMaxObserved_dB', NaN), ...
        localField(r, 'GMSKSecondOrderPLLApplied', false), ...
        localField(r, 'GMSKSecondOrderPLLLocked', false), ...
        localField(r, 'GMSKSecondOrderPLLFinalFrequency_Hz', NaN), ...
        localField(r, 'GMSKSecondOrderPLLFrequencyMin_Hz', NaN), ...
        localField(r, 'GMSKSecondOrderPLLFrequencyMax_Hz', NaN), ...
        localField(r, 'GMSKSecondOrderPLLUpdateAcceptanceRate', NaN), ...
        localField(r, 'GMSKSecondOrderPLLFadeHoldSamples', NaN), ...
        localField(r, 'GMSKSecondOrderPLLMeanAbsPhaseError', NaN), ...
        localField(r, 'GMSKResidualTrackerApplied', false), ...
        localField(r, 'GMSKResidualWindowCount', NaN), ...
        localField(r, 'GMSKResidualAcceptedWindows', NaN), ...
        localField(r, 'GMSKResidualHoldWindows', NaN), ...
        localField(r, 'GMSKResidualMedian_Hz', NaN), ...
        localField(r, 'GMSKResidualRMS_Hz', NaN), ...
        localField(r, 'GMSKResidualMedianConfidence_dB', NaN), ...
        localField(r, 'GMSKResidualCandidateFiniteRate', NaN), ...
        localField(r, 'GMSKResidualCandidateMedian_Hz', NaN), ...
        localField(r, 'GMSKResidualCandidateRMS_Hz', NaN), ...
        localField(r, 'GMSKResidualConfidenceRejectedWindows', NaN), ...
        localField(r, 'GMSKResidualRangeRejectedWindows', NaN), ...
        localField(r, 'GMSKResidualRawAcceptedRate', NaN), ...
        localField(r, 'GMSKResidualRawMin_Hz', NaN), ...
        localField(r, 'GMSKResidualRawMedian_Hz', NaN), ...
        localField(r, 'GMSKResidualRawMax_Hz', NaN), ...
        localField(r, 'GMSKResidualRawRMS_Hz', NaN), ...
        localField(r, 'GMSKResidualJumpMax_Hz', NaN), ...
        localField(r, 'GMSKResidualJumpRMS_Hz', NaN), ...
        localField(r, 'GMSKResidualPhaseCorrectionEnd_deg', NaN), ...
        string(localStructChar(r, 'QualityMetricType', '')), ...
        string(localGMSKDetectorUsed(r, p, modType)), ...
        logical(ok), ...
        string(status), ...
        string(err), ...
        double(elapsed)};
end

function names = localVariableNames()
    names = {'CaseIndex', ...
        'Scenario', 'ModType', 'ChannelCoding', 'Rate', ...
        'RandomizerEnabled','RandomizerFECPosition','DataPathMode', ...
        'TMDataSource','TMDataSourceI','TMDataSourceQ', ...
        'ConvolutionalG1G2Mode','RequestedCFO_Hz', ...
        'CarrierCaptureRangeConfigured_Hz', ...
        'RequestedPhaseOffset_deg','RequestedDelay_samples', ...
        'NumBytesInTransferFrame', 'NumBitsInInformationBlock', ...
        'IsLDPCOnSMTF', 'TPCBlocksPerTF', ...
        'HEnabled', 'EqualizerEnabled', 'NormalizeHChannel', ...
        'NormalizeEqualizerOutput', ...
        'BER', 'LockRate_pct', 'FER', 'CountedFrames', 'MatchedFrames', ...
        'FrameDuration_s', 'MatchedDuration_s', 'CountedDuration_s', ...
        'EVM_post_pct','EVMRadial_pct','EVMTangential_pct', ...
        'ResidualPhaseRMS_deg','ResidualRadiusRMS_dB', ...
        'MER_dB', 'SNR_est_dB', 'ResidualCFO_Hz', ...
        'HGain_dB', 'HNormalizationGain_dB', 'HMeanCoeffMagnitude', ...
        'HOutOfRangeMode', 'HSourceDuration_s', 'WaveformDuration_s', ...
        'ExceedsHDuration', 'HResponseMode', 'HApplyPMode', ...
        'NoisePlacement', 'NoiseMode', 'NoisePSD_dBmHz', ...
        'NoiseBandwidthHz', 'NoisePower_dBm', 'NoiseEquivalentSNR_dB', ...
        'ConverterChainEnabled','BasebandIFLevel_dBm', ...
        'UpconverterNetGain_dB','UpconverterAttenuation_dB', ...
        'UpconverterOutputLevel_dBm', ...
        'UpconverterCompressionRisk','HAppliedGain_dB', ...
        'DownconverterInputLevel_dBm','DownconverterNetGain_dB', ...
        'DownconverterAttenuation_dB','DownconverterAutoAttenuation', ...
        'DownconverterOutputLevel_dBm', ...
        'DownconverterInputWithinTypicalRange', ...
        'DownconverterCompressionRisk','ADCEquivalentEnabled', ...
        'ADCRMSBackoff_dB','ADCClip_pct', ...
        'EqualizerMode','FastEnvelopeEstimatorMode', ...
        'FastEnvelopeTauSymbols','FastEnvelopeBlockSymbols', ...
        'FastEnvelopeHopSymbols','FastEnvelopeGainSlewDBPerSymbol', ...
        'FastEnvelopeMinGainLimit_dB','FastEnvelopeMaxGainLimit_dB', ...
        'FastEnvelopeObservedMin_dB','FastEnvelopeObservedMax_dB', ...
        'BlindReliabilityApplied','BlindReliabilityFinalState', ...
        'BlindReliabilityHoldFraction_pct', ...
        'BlindReliabilityHoldEvents','BlindReliabilityRecoverEvents', ...
        'BlindReliabilityMinRelativePower_dB', ...
        'BlindReliabilityMaxInverseGain_dB', ...
        'DDWindowSymbols', 'DDMinWindowAcceptance', ...
        'DDPassesEffective', 'ScalarDDPassesConfigured', ...
        'DecisionGate', 'CMASwitchMSE', 'CMAMSE', ...
        'DDAcceptanceRate_pct', 'DDMSE', ...
        'ASMTrainingCount','ASMTrainingUpdates', ...
        'ASMTrainingScoreBefore','ASMTrainingScoreAfter', ...
        'PredecoderBER', 'PredecoderOffset', 'PredecoderPolarity', ...
        'PredecoderTxFrameOffset', 'PredecoderASMAligned', ...
        'PredecoderBitErrors', 'PredecoderBitsCompared', ...
        'PredecoderSteadyBER', 'PredecoderSteadyBitErrors', ...
        'PredecoderSteadyBitsCompared', 'PredecoderFramesCompared', ...
        'PredecoderFrameBERP95', 'PredecoderFrameBERMax', ...
        'ASMFramePhaseCorrectionEnabled', ...
        'ASMFramePhaseCorrectionApplied', ...
        'ASMFramePhaseCorrectionFrames', ...
        'ASMFramePhaseCorrectionReliableFrames', ...
        'ASMFramePhaseCycleSlipsBefore', ...
        'ASMFramePhaseCycleSlipsAfter', ...
        'DDWindowCount', 'DDGoodWindows', ...
        'DDHoldWindows', 'DDFadeHoldWindows', ...
        'DDFadeEnterEvents','DDFadeRecoverEvents', ...
        'PilotDataFadeSymbols','PilotDataFadeFraction_pct', ...
        'ExternalFadeMaskProvided','ExternalFadeMaskLengthMatched', ...
        'ExternalFadeMaskInputLength','ExternalFadeInputSymbols', ...
        'ExternalFadeExpandedSymbols','DDExternalFadeHoldWindows', ...
        'DDExternalFadeHoldSymbols', ...
        'HighRatePhaseTrackingApplied','HighRatePhaseWindowSymbols', ...
        'HighRatePhaseMeanConfidence','HighRatePhaseHoldSamples', ...
        'UQPSKPostCarrierEQEnabled', ...
        'APSKReceiverMode', ...
        'QAMBlindPhaseSearchApplied', ...
        'QAMBlindPhaseSearchReliableRate_pct', ...
        'QAMBlindPhaseSearchMedianMetric', ...
        'QAMBlindPhaseSearchFinalCorrection_deg', ...
        'QAMBlindPhaseSearchFadeHoldBlocks', ...
        'QAMBlindPhaseSearchFadeEvents', ...
        'QAMBlindPhaseSearchFadeRecoveries', ...
        'QAMBlindPhaseSearchReacquisitions', ...
        'QAMBlindPhaseSearchInitialFrequencyRadPerSymbol', ...
        'QAMPowerGainApplied','QAMPowerGainAcceptanceRate_pct', ...
        'QAMPowerGainRegularization','QAMPowerGainMaxInverseGainDB', ...
        'QAMPowerGainInverseMaxObserved_dB', ...
        'PilotlessAPSKApplied', ...
        'PilotlessAPSKCoarsePowerOrder', ...
        'PilotlessAPSKFourthPowerCFO_Hz', ...
        'PilotlessAPSKFourthPowerConfidence_dB', ...
        'PilotlessAPSKNDAResidualCFO_Hz', ...
        'PilotlessAPSKNDAResidualCFOApplied', ...
        'PilotlessAPSKMthPowerPhaseTrackerApplied', ...
        'PilotlessAPSKMthPowerPhaseFinalCorrection_deg', ...
        'PilotlessAPSKMthPowerPhaseMedianConfidence', ...
        'PilotlessAPSKBlindPhaseSearchApplied', ...
        'PilotlessAPSKBlindPhaseSearchReliableRate_pct', ...
        'PilotlessAPSKBlindPhaseSearchMedianMetric', ...
        'PilotlessAPSKBlindPhaseSearchFinalCorrection_deg', ...
        'PilotlessAPSKPreDDGainApplied', ...
        'PilotlessAPSKPreDDGainAcceptanceRate_pct', ...
        'PilotlessAPSKPreDDGainHoldFraction_pct', ...
        'PilotlessAPSKPreDDGainFadeFraction_pct', ...
        'PilotlessAPSKPreDDGainFinalMagnitude_dB', ...
        'PilotlessAPSKRingNormalizerApplied', ...
        'PilotlessAPSKRingEstimatorMode', ...
        'PilotlessAPSKRingAcceptanceRate_pct', ...
        'PilotlessAPSKRingHoldFraction_pct', ...
        'PilotlessAPSKRingFadeFraction_pct', ...
        'PilotlessAPSKRingFinalAmplitude_dB', ...
        'PilotlessAPSKCarrierAcceptanceRate_pct', ...
        'PilotlessAPSKCarrierHoldFraction_pct', ...
        'PilotlessAPSKCarrierPhaseErrorRMS_deg', ...
        'PilotlessAPSKResidualFrequency_Hz', ...
        'PilotlessAPSKGainAcceptanceRate_pct', ...
        'PilotlessAPSKGainRegularization', ...
        'PilotlessAPSKGainMaxInverseGainDB', ...
        'PilotlessAPSKGainInverseMaxObserved_dB', ...
        'GMSKSecondOrderPLLApplied','GMSKSecondOrderPLLLocked', ...
        'GMSKSecondOrderPLLFinalFrequency_Hz', ...
        'GMSKSecondOrderPLLFrequencyMin_Hz', ...
        'GMSKSecondOrderPLLFrequencyMax_Hz', ...
        'GMSKSecondOrderPLLUpdateAcceptanceRate', ...
        'GMSKSecondOrderPLLFadeHoldSamples', ...
        'GMSKSecondOrderPLLMeanAbsPhaseError', ...
        'GMSKResidualTrackerApplied','GMSKResidualWindowCount', ...
        'GMSKResidualAcceptedWindows','GMSKResidualHoldWindows', ...
        'GMSKResidualMedian_Hz','GMSKResidualRMS_Hz', ...
        'GMSKResidualMedianConfidence_dB', ...
        'GMSKResidualCandidateFiniteRate', ...
        'GMSKResidualCandidateMedian_Hz', ...
        'GMSKResidualCandidateRMS_Hz', ...
        'GMSKResidualConfidenceRejectedWindows', ...
        'GMSKResidualRangeRejectedWindows', ...
        'GMSKResidualRawAcceptedRate','GMSKResidualRawMin_Hz', ...
        'GMSKResidualRawMedian_Hz','GMSKResidualRawMax_Hz', ...
        'GMSKResidualRawRMS_Hz','GMSKResidualJumpMax_Hz', ...
        'GMSKResidualJumpRMS_Hz','GMSKResidualPhaseCorrectionEnd_deg', ...
        'QualityMetricType', ...
        'GMSKDetectorUsed', ...
        'Success', 'Status', 'ErrorMessage', 'Runtime_s'};
end

function duration_s = localFrameDurationSeconds(modType, p)
    duration_s = NaN;
    symbolRate = localStructNumeric(p, 'symbolRate', NaN);
    numBytes = localStructNumeric(p, 'NumBytesInTransferFrame', NaN);
    bps = localBitsPerSymbol(modType);
    codeRate = localCodeRate(p);
    if isfinite(symbolRate) && symbolRate > 0 && ...
            isfinite(numBytes) && numBytes > 0 && ...
            isfinite(bps) && bps > 0 && ...
            isfinite(codeRate) && codeRate > 0
        duration_s = (numBytes * 8) / codeRate / bps / symbolRate;
    end
end

function bps = localBitsPerSymbol(modType)
    key = upper(string(modType));
    if contains(key, '32QAM') || contains(key, '32APSK')
        bps = 5;
    elseif contains(key, '16QAM') || contains(key, '16APSK')
        bps = 4;
    elseif contains(key, '8PSK')
        bps = 3;
    elseif contains(key, 'QPSK')
        bps = 2;
    else
        bps = 1;
    end
end

function rate = localCodeRate(p)
    code = lower(string(localStructChar(p, 'channelCoding', 'none')));
    if contains(code, 'convolutional')
        rate = localRateStringToDouble(localStructChar(p, 'ConvolutionalCodeRate', '1/2'), 1/2);
    elseif contains(code, 'turbo') || contains(code, 'ldpc')
        rate = localRateStringToDouble(localStructChar(p, 'CodeRate', '1/2'), 1/2);
    elseif contains(code, 'rs')
        rate = 223/255;
    elseif contains(code, 'tpc')
        rate = localRateStringToDouble(localStructChar(p, 'TPCCodeRate', '1'), 1);
    else
        rate = 1;
    end
end

function rate = localRateStringToDouble(rawRate, defaultRate)
    rate = defaultRate;
    text = strtrim(char(string(rawRate)));
    parts = split(string(text), '/');
    if numel(parts) == 2
        num = str2double(parts(1));
        den = str2double(parts(2));
        if isfinite(num) && isfinite(den) && den ~= 0
            rate = num / den;
        end
    else
        val = str2double(text);
        if isfinite(val) && val > 0
            rate = val;
        end
    end
end

function value = localStructNumeric(s, fieldName, defaultValue)
    value = defaultValue;
    if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
        value = double(s.(fieldName));
    end
end

function value = localStructChar(s, fieldName, defaultValue)
    value = defaultValue;
    if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
        value = char(string(s.(fieldName)));
    end
end

function detector = localGMSKDetectorUsed(result, params, modType)
    detector = 'not-applicable';
    if ~strcmpi(string(modType), "GMSK")
        return;
    end
    if isstruct(result) && isfield(result, 'GMSKDetectorUsed') && ...
            ~isempty(result.GMSKDetectorUsed)
        detector = char(string(result.GMSKDetectorUsed));
        return;
    end
    detector = localStructChar(params, 'GMSKDetectionMode', ...
        'official-viterbi-frame-reset');
    if strcmpi(detector, 'official-viterbi-frame-reset')
        detector = 'official';
    end
end

function v = localField(s, fieldName, defaultValue)
    v = defaultValue;
    if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
        v = s.(fieldName);
        if islogical(v)
            v = double(v);
        end
        if ischar(v) || isstring(v)
            n = str2double(char(v));
            if isfinite(n)
                v = n;
            else
                v = defaultValue;
            end
        end
    end
end

function localPrintWeakCases(T, opts)
    if isempty(T)
        fprintf('\nNo cases were executed.\n');
        return;
    end

    pending = T.Status == "PENDING" | T.Status == "RUNNING";
    weak = ~pending & (~T.Success | T.BER < 0 | isnan(T.BER) | isnan(T.LockRate_pct));
    if ~isempty(opts.maxGoodBER)
        weak = weak | (~pending & T.BER > opts.maxGoodBER);
    end
    if ~isempty(opts.minGoodLockPct)
        weak = weak | (~pending & T.LockRate_pct < opts.minGoodLockPct);
    end
    if ~isempty(opts.minGoodMERdB)
        merApplicable = ~ismember(upper(string(T.ModType)), ...
            ["MSK","GMSK"]);
        weak = weak | (~pending & merApplicable & ...
            (isnan(T.MER_dB) | T.MER_dB < opts.minGoodMERdB));
    end
    if ~isempty(opts.maxGoodFER)
        weak = weak | (~pending & (isnan(T.FER) | T.FER > opts.maxGoodFER));
    end
    W = T(weak, :);

    fprintf('\n==== Weak / failed cases ====\n');
    if isempty(W)
        fprintf('None under the configured PASS thresholds.\n');
        if any(pending)
            fprintf('%d case(s) remain pending and were not classified as failures.\n', nnz(pending));
        end
        return;
    end

    cols = {'Scenario','ModType','ChannelCoding','Rate','BER','LockRate_pct', ...
        'EVM_post_pct','MER_dB','CountedFrames','Success','ErrorMessage'};
    disp(W(1:min(height(W), 30), cols));
    if height(W) > 30
        fprintf('... %d more weak cases in the CSV.\n', height(W) - 30);
    end
end

function tag = localTMDataSourceCaseTag(params)
    base = string(localStructChar(params, 'TMDataSource', 'random'));
    pathMode = string(localStructChar(params, 'DataPathMode', 'single'));
    if strcmpi(pathMode, 'single')
        tag = base;
        return;
    end
    sourceI = string(localStructChar(params, 'TMDataSourceI', ''));
    sourceQ = string(localStructChar(params, 'TMDataSourceQ', ''));
    if strlength(sourceI) == 0
        sourceI = base;
    end
    if strlength(sourceQ) == 0
        sourceQ = base;
    end
    if strcmpi(sourceI, 'random') && strcmpi(sourceQ, 'random')
        tag = "random";
    else
        tag = "I-" + sourceI + "-Q-" + sourceQ;
    end
end

function id = localId(text)
    id = lower(regexprep(string(text), '[^a-zA-Z0-9]+', '.'));
    id = strip(id, '.');
end

function localWriteTable(T, pathValue)
    outputDir = fileparts(pathValue);
    temporaryPath = [tempname(outputDir), '.csv'];
    cleanup = onCleanup(@() localDeleteIfPresent(temporaryPath));
    writetable(T, temporaryPath);
    [ok, message] = movefile(temporaryPath, pathValue, 'f');
    if ~ok
        warning('sweep_h_channel_short_frames:SummaryWriteFailed', ...
            'Could not write "%s": %s', pathValue, message);
    end
    clear cleanup;
end

function localSaveFinalMat(pathValue, T, opts, cases)
    outputDir = fileparts(pathValue);
    temporaryPath = [tempname(outputDir), '.mat'];
    cleanup = onCleanup(@() localDeleteIfPresent(temporaryPath));
    save(temporaryPath, 'T', 'opts', 'cases', '-v7.3');
    [ok, message] = movefile(temporaryPath, pathValue, 'f');
    if ~ok
        warning('sweep_h_channel_short_frames:MatWriteFailed', ...
            'Could not write "%s": %s', pathValue, message);
    end
    clear cleanup;
end

function localDeleteIfPresent(pathValue)
    if exist(pathValue, 'file') == 2
        delete(pathValue);
    end
end
