function test_4d_tcm_regression()
%TEST_4D_TCM_REGRESSION Basic 4D-8PSK-TCM regression checks.

    fprintf('\n==== 4D-8PSK-TCM regression ====\n');

    fprintf('\n-- ideal_demapper --\n');
    rng(1);
    effList = [2 2.25 2.5 2.75];
    for eff = effList
        bitsPerGroup = round(4 * eff);
        nBits = bitsPerGroup * 80;
        txBits = int8(randi([0 1], nBits, 1));
        [sym, ~, ~] = satcom.internal.ccsds.fourD8PSKTCMMod( ...
            txBits, eff, zeros(6,1,'int8'), zeros(3,1,'int8'));
        demod = HelperCCSDSTMDemodulator( ...
            'Modulation','4D-8PSK-TCM', ...
            'ChannelCoding','none', ...
            'ModulationEfficiency',eff);
        demodSoft = demod(sym);
        rxBits = int8(demodSoft > 0);
        nErr = sum(rxBits(1:nBits) ~= txBits);
        fprintf('eff=%.2f ideal demapper errors=%d/%d\n', eff, nErr, nBits);
        assert(nErr == 0, ...
            '4D-TCM ideal demapper failed for eff=%.2f: errors=%d/%d.', ...
            eff, nErr, nBits);
    end

    fprintf('\n-- impaired_full_chain --\n');
    p = struct( ...
        'modType','4D-8PSK-TCM', ...
        'symbolRate',1e6, ...
        'sps',8, ...
        'snr',20, ...
        'cfo',20000, ...
        'phaseOffset',15, ...
        'delay',0, ...
        'channelCoding','none', ...
        'ModulationEfficiency',2, ...
        'NumBytesInTransferFrame',1115, ...
        'hasASM',true, ...
        'hasRandomizer',false, ...
        'showFigures',false, ...
        'berWarmUpFrames',2, ...
        'berFrames',5);

    out = run_ccsds_tm_evaluation(p);
    r = jsondecode(out);

    fprintf('BER=%g, Lock=%g, BestTCMSkip=%d\n', ...
        r.BER, r.LockRate, r.BestTCMSkip);

    assert(r.BER <= 5e-3, ...
        '4D-TCM full-chain regression failed: BER=%g > 5e-3.', r.BER);
    assert(r.LockRate >= 0.95, ...
        '4D-TCM full-chain regression failed: Lock=%g < 0.95.', r.LockRate);
    assert(r.BestTCMSkip == 3, ...
        '4D-TCM full-chain regression failed: expected BestTCMSkip=3, got %d.', ...
        r.BestTCMSkip);

    fprintf('\nPASS: 4D-8PSK-TCM regression passed.\n');
end
