function capabilities = tm_data_path_capabilities()
%TM_DATA_PATH_CAPABILITIES Ordinary-TM dual-I/Q support contract.
%
% Keep the implementation guard, fast contract tests, and user-facing
% support report synchronized through this single catalog.

    capabilities = struct( ...
        'ContractVersion', "tm-data-path-v2", ...
        'InputLayout', "[all I-rail frames; all Q-rail frames]", ...
        'EncodedLayout', "I1,Q1,I2,Q2,...", ...
        'DecodedFrameLayout', "I-frame-1,Q-frame-1,I-frame-2,Q-frame-2,...", ...
        'RequiresEqualRailLengths', true, ...
        'SupportedModulations', ...
            ["QPSK","OQPSK","8PSK","16QAM","32QAM"], ...
        'AddNextModulations', ...
            ["16APSK","32APSK"], ...
        'SeparateDesignModulations', ...
            ["UQPSK","4D-8PSK-TCM"], ...
        'NotApplicableModulations', ...
            ["PCM/PSK/PM","PCM/PM/biphase-L","BPSK","GMSK","FM"], ...
        'SupportedCodings', ...
            ["none","RS","convolutional","LDPC","turbo"], ...
        'AddNextCodings', ...
            ["TPC","concatenated"], ...
        'SeparateWaveformPaths', ...
            ["FACM","LDPC-on-SMTF"]);

    capabilities.AllOrdinaryTMModulations = [ ...
        capabilities.SupportedModulations, ...
        capabilities.AddNextModulations, ...
        capabilities.SeparateDesignModulations, ...
        capabilities.NotApplicableModulations];
    capabilities.AllOrdinaryTMCodings = [ ...
        capabilities.SupportedCodings, ...
        capabilities.AddNextCodings];

    capabilities.UnequalDualIQ = struct( ...
        'DataPathMode', "unequalDualIQ", ...
        'Modulation', "UQPSK", ...
        'RRatio', 2, ...
        'ARatio', 2, ...
        'InputLayout', ...
            "[all I-rail frames (2N); all Q-rail frames (N)]", ...
        'EncodedLayout', "I1,I2,Q1,I3,I4,Q2,...", ...
        'DecodedFrameLayout', ...
            "I-frame-1,I-frame-2,Q-frame-1,...", ...
        'RequiresEqualRailLengths', false, ...
        'SupportedCodings', capabilities.SupportedCodings, ...
        'Status', "EXPERIMENTAL");

    % Rate/profile coverage used by the fast dual-I/Q generator contract.
    % RS is profile-based rather than rate-only. Keep this list conservative:
    % it contains configurations that are already part of the formal TM
    % sweep, not every value accepted by the underlying System object.
    capabilities.SupportedConvolutionalRates = ...
        ["1/2","2/3","3/4","5/6","7/8"];
    capabilities.SupportedLDPCRates = ["1/2","2/3","4/5"];
    capabilities.SupportedTurboRates = ["1/2","1/3","1/4","1/6"];
    capabilities.SupportedRSProfiles = struct( ...
        'Rate', "223/255", ...
        'RSMessageLength', 223, ...
        'RSInterleavingDepth', 1, ...
        'IsRSMessageShortened', false, ...
        'RSShortenedMessageLength', 223);
end
