clc;
clear;
close all;

sps = 8;
symbolRate = 10e6;
Fs = sps*symbolRate;
snr = 12;

numFrames = 10;
cfo = 50000;
phaseOffset = 10;
delay = 0.3;
base = struct('modType','16QAM', ...
    'symbolRate',symbolRate, ...
    'sps',sps, ...
    'snr',snr, ...
    'cfo',cfo, ...
    'phaseOffset',10, ...
    'delay',0.3, ...
    'channelCoding','none', ...
    'NumBytesInTransferFrame',1115, ...
    'RolloffFactor',0.35, ...
    'hasASM',true, ...
    'hasRandomizer',false, ...
    'showFigures',false, ...
    'berWarmUpFrames',5, ...
    'berFrames',20, ...
    'enableHChannel',true, ...
    'HMode','siso_multipath', ...
    'normalizeHChannel',true);
args = { ...
    "WaveformSource","synchronization and channel coding", ...
    "ChannelCoding",base.channelCoding, ...
    "Modulation",base.modType, ...
    "NumBytesInTransferFrame",base.NumBytesInTransferFrame, ...
    "SamplesPerSymbol",base.sps, ...
    "HasASM",base.hasASM, ...
    "HasRandomizer",base.hasRandomizer, ...
    "PulseShapingFilter","root raised cosine", ...
    "RolloffFactor",base.RolloffFactor, ...
    "FilterSpanInSymbols",10};

txWaveGen = ccsdsTMWaveformGenerator(args{:});

disp(info(txWaveGen));

% 发送端波形
data = randi([0,1],txWaveGen.NumInputBits*numFrames,1,'int8');
[txWaveform,encodedBits] = txWaveGen(data);
rxWaveform = txWaveform;
fprintf('numinputBits : %d\n',txWaveGen.NumInputBits);

if cfo ~= 0 || phaseOffset ~= 0
    pfo = comm.PhaseFrequencyOffset( ...
        'FrequencyOffset', cfo, ...
        'PhaseOffset', phaseOffset, ...
        'SampleRate', Fs);

    rxWaveform = pfo(rxWaveform);
end

if delay ~= 0
    vfd = dsp.VariableFractionalDelay('InterpolationMethod','Farrow');
    rxWaveform = vfd(rxWaveform, delay);
end

rxWaveform = awgn(rxWaveform,snr,'measured');

txRawSym = txWaveform(1:sps:end);
rxRawSym = rxWaveform(1:sps:end);

numPlot = 2000;
txRawSym = txRawSym/sqrt(mean(abs(txRawSym).^2)+eps);
rxRawSym = rxRawSym/sqrt(mean(abs(rxRawSym).^2)+eps);
txRawPlot = txRawSym(1:min(numPlot,numel(txRawSym)));
rxRawPlot = rxRawSym(1:min(numPlot,numel(rxRawSym)));
figure()
scatter(real(txRawPlot), imag(txRawPlot), 8, 'filled');
grid on;
axis equal;
xlabel('I');
ylabel('Q');
title('发送端 raw 星座：txWaveform(1:sps:end)');