function scrambledOut = randomizer(data)
%SATCOM.INTERNAL.CCSDS.RANDOMIZER Randomization as per CCSDS TC 
%
%   Note: This is an internal undocumented function and its API and/or
%   functionality may change in subsequent releases.
%
%   SCRAMBLEDOUT = SATCOM.INTERNAL.CCSDS.RANDOMIZER(DATA) returns the
%   randomized bits, SCRAMBLEDOUT generated by the XOR operation of the
%   input bits, DATA with the random sequence generated as per the CCSDS TC
%   recommendation.

%   Copyright 2020 The MathWorks, Inc.

% References
% [1] TC Synchronization and Channel Coding. Recommendation for Space Data
% System Standards, CCSDS 231.0-B-3. Blue Book. Issue 3. Washington, D.C.:
% CCSDS, September 2017.

%#codegen

% Random sequence generation
pnSequence  = comm.PNSequence('Polynomial',[1 0 1 0 1 1 1 1 1],...
    'SamplesPerFrame',255,'InitialConditions',[1 1 1 1 1 1 1 1]);
rndSeq = pnSequence();

% Randomize the TC transfer frames 
len = length(data);
numRepetitions = ceil(len/255);
repSeq = repmat(rndSeq,numRepetitions,1);
scrambledOut = double(xor(data,repSeq(1:len)));

end