function syn = syndrome(code, n, genpolyroots, e2p, p2e)
%SATCOM.INTERNAL.CCSDS.SYNDROME calculate the syndrome for RS codes
%   SYN = SATCOM.INTERNAL.CCSDS.SYNDROME(CODE, N, GENPOLYROOTS, E2P, P2E)
%   calculates the syndrome for the received RS code CODE. N is number of
%   non-zero finite elements that the Galois Field has. GENPOLYROOTS is a
%   vector of roots in ascending order. Typically they are in the form of
%   alpha^(h*(b+j)) where 'j' goes from 0 to 2*t where 't' is number of
%   correctable errors. For narrow-sense codes, b = 1. In case of CCSDS, h
%   is 11. For k = 223, b = 112 and for k = 239, b = 120. And GENPOLYROOTS
%   can be generated by GENPOLYROOTS = mod(h*(b:b+t2-1), N). SYN is the
%   syndrome vector where each element represents coefficient of the
%   syndrome polynomial with the first element representing coefficient of
%   z^0 of syndrome polynomial. Each element of SYN is represented in power
%   form in GF(N+1). E2P is a table which converts the exponential form of
%   symbols to polynomial form and P2E is a table which converts polynomial
%   form of symbols to exponential form.
%
%   Note: This is an internal undocumented function and its API and/or
%   functionality may change in subsequent releases.

%   Copyright 2019-2020 The MathWorks, Inc.

%#codegen

t2 = length(genpolyroots);
% t = t2/2;

% 'code' is in polynomial form. Convert that to exponential form
% Considering the following notation for processing each element in gf:
% * In exponent form, 'zero' is equivalent to zero in polynomial form
% * In polynomial form, 'one' is equivalent to 'n' in exponent form
% * Need to track if a variable is in exponent form or in polynomial form
cpower = code;
cpower(code~=0) = p2e(code(code~=0)); % As zeros in polynomial form and 
                                      % exponential form are equivalent,
                                      % convert to exponential form only
                                      % those elements which are not zero.
cpower(code==1) = n; % As one in polynomial form is equivalent to 'n' in exponential form

% Calculate each syndrome value in a loop
syn = code(end)*ones(t2, 1, 'int32'); % In Polynomial form. Later convert to exponential form
for icode = 1:length(code)-1
    codeEle = cpower(end-icode); % When processed from the end of the code, no need to append zeros when shortening is performed
    for isyn = 1:t2
        if (codeEle~=0 && genpolyroots(isyn)~=0)
            mulval = mod(codeEle + icode*genpolyroots(isyn), n);
            if (mulval==0)
                mulval = n;
            end
            syn(isyn) = bitxor(syn(isyn), e2p(mulval));
        end
        
    end
end
syn(syn==1) = -1;
syn(syn~=-1 & syn~=0) = p2e(syn(syn~=-1 & syn~=0));
syn(syn==-1) = n;
end
