function results = reg_coding_smoke()
%REG_CODING_SMOKE Quick checks that selected modulation/coding paths connect.

    reg_setup(4);

    cases = {
        struct('Name',"QPSK none", 'P', struct( ...
            'modType','QPSK','channelCoding','none','NumBytesInTransferFrame',1115, ...
            'RolloffFactor',0.35,'snr',20,'cfo',10000,'phaseOffset',10,'delay',0.1), ...
            'MaxBER',1e-3,'MinLock',0.95)
        struct('Name',"8PSK convolutional", 'P', struct( ...
            'modType','8PSK','channelCoding','convolutional','NumBytesInTransferFrame',1115, ...
            'ConvolutionalCodeRate','2/3','RolloffFactor',0.35, ...
            'snr',14,'cfo',20000,'phaseOffset',10,'delay',0.2), ...
            'MaxBER',5e-3,'MinLock',0.90)
        struct('Name',"PCM/PSK/PM RS", 'P', struct( ...
            'modType','PCM/PSK/PM','channelCoding','RS', ...
            'RSMessageLength',223,'RSInterleavingDepth',1,'IsRSMessageShortened',false, ...
            'PCMFormat','NRZ-L','SubcarrierWaveform','sine','SubcarrierToSymbolRateRatio',2, ...
            'ModulationIndex',pi/3,'snr',8,'cfo',20000,'phaseOffset',10,'delay',0.2), ...
            'MaxBER',5e-3,'MinLock',0.80)
        struct('Name',"PCM/PM/biphase-L convolutional", 'P', struct( ...
            'modType','PCM/PM/biphase-L','channelCoding','convolutional', ...
            'NumBytesInTransferFrame',1115,'ConvolutionalCodeRate','2/3', ...
            'ModulationIndex',pi/3,'snr',12,'cfo',200000,'phaseOffset',10,'delay',0.2), ...
            'MaxBER',1e-3,'MinLock',0.95)
        struct('Name',"4D-TCM none", 'P', struct( ...
            'modType','4D-8PSK-TCM','channelCoding','none','NumBytesInTransferFrame',1112, ...
            'ModulationEfficiency',2.25,'snr',20,'cfo',20000,'phaseOffset',15,'delay',0.3), ...
            'MaxBER',1e-3,'MinLock',0.95)
    };

    results = table(strings(0,1), strings(0,1), strings(0,1), zeros(0,1), ...
        zeros(0,1), strings(0,1), false(0,1), ...
        'VariableNames', {'Case','Modulation','Coding','BER','LockRate_pct', ...
        'Status','Pass'});

    fprintf('\n================ REG CODING SMOKE ================\n');

    for k = 1:numel(cases)
        c = cases{k};
        p = c.P;
        p.symbolRate = 1e6;
        p.sps = 8;
        p.hasASM = true;
        p.hasRandomizer = false;
        p.showFigures = false;
        p.berWarmUpFrames = 3;
        p.berFrames = 8;

        fprintf('\n[CODING] case=%s\n', c.Name);
        out = reg_decode_output(run_ccsds_tm_evaluation(p));

        pass = out.BER <= c.MaxBER && out.LockRate >= c.MinLock;
        status = "PASS";
        if ~pass
            status = "FAIL";
        end

        results = [results; {c.Name, string(p.modType), string(p.channelCoding), ...
            out.BER, out.LockRate*100, status, pass}]; %#ok<AGROW>
    end

    disp(results);
    assert(all(results.Pass), 'Coding smoke regression failed.');
end
