function [M, imagePaths] = run_tm_apsk_tdl_turbo_debug(userOpts)
%RUN_TM_APSK_TDL_TURBO_DEBUG Reproduce the unstable 32APSK TDL Turbo case.
%
%   [M, imagePaths] = run_tm_apsk_tdl_turbo_debug;
%
% The default seed is the failing paired-sweep seed. Debug output is on,
% while figures are off by default. Set ShowFigures=true to inspect plots
% or Debug=false when comparing several seeds quietly.

    if nargin < 1 || isempty(userOpts)
        userOpts = struct();
    end
    if ~isstruct(userOpts)
        error('run_tm_apsk_tdl_turbo_debug:InvalidOptions', ...
            'userOpts must be a struct.');
    end

    thisDir = fileparts(mfilename('fullpath'));
    sourceDir = fileparts(thisDir);
    addpath(thisDir);
    addpath(sourceDir);

    cfg = struct( ...
        'Seed',769864844, ...
        'SNR',35, ...
        'CFO',20000, ...
        'PhaseOffset',10, ...
        'Delay',0.2, ...
        'SymbolRate',1e6, ...
        'SamplesPerSymbol',8, ...
        'BERWarmUpFrames',8, ...
        'BERFrames',16, ...
        'EnableAPSKCoarseFrequencyCompensator',true, ...
        'Debug',true, ...
        'ShowFigures',false, ...
        'ChannelFile','E:/matlab_project/v3.0/v3.0/channel/2-ChannelData.mat');
    cfg = localApplyOptions(cfg, userOpts);

    if exist(char(cfg.ChannelFile), 'file') ~= 2
        error('run_tm_apsk_tdl_turbo_debug:MissingChannelFile', ...
            'Missing TDL channel file: %s', char(cfg.ChannelFile));
    end

    rng(double(cfg.Seed), 'twister');
    p = struct( ...
        'modType','32APSK', ...
        'DataPathMode','dualIQ', ...
        'symbolRate',double(cfg.SymbolRate), ...
        'sps',double(cfg.SamplesPerSymbol), ...
        'snr',double(cfg.SNR), ...
        'cfo',double(cfg.CFO), ...
        'phaseOffset',double(cfg.PhaseOffset), ...
        'delay',double(cfg.Delay), ...
        'channelCoding','turbo', ...
        'CodeRate','1/2', ...
        'NumBitsInInformationBlock',1784, ...
        'RandomizerEnabled',true, ...
        'RandomizerFECPosition','afterEncoding', ...
        'RolloffFactor',0.35, ...
        'hasASM',true, ...
        'HasTMAPSKPilots',true, ...
        'enableAPSKCoarseFrequencyCompensator', ...
            logical(cfg.EnableAPSKCoarseFrequencyCompensator), ...
        'berWarmUpFrames',double(cfg.BERWarmUpFrames), ...
        'berFrames',double(cfg.BERFrames), ...
        'enableHChannel',true, ...
        'HMode','h_matrix_file', ...
        'channelFilePath',char(cfg.ChannelFile), ...
        'channelInterpolationMethod','linear', ...
        'channelOutOfRangeMode','wrap', ...
        'interpolateChannelDelays',false, ...
        'normalizeHChannel',false, ...
        'enableEqualizer',true, ...
        'equalizerMode','mmse', ...
        'normalizeEqualizerOutput',true, ...
        'splitPathDebug',logical(cfg.Debug), ...
        'debugASMPhase',logical(cfg.Debug), ...
        'debugCodedBoundary',logical(cfg.Debug), ...
        'debugPerFrameBERSummary',logical(cfg.Debug), ...
        'debugPerFrameBERFormat','scientific', ...
        'debugPerFrameBERNonzeroCount',64, ...
        'showFigures',logical(cfg.ShowFigures), ...
        'showPipelineFigure',logical(cfg.ShowFigures), ...
        'showPowerFigure',false, ...
        'showDamageBudgetFigure',false);

    if logical(cfg.Debug)
        fprintf(['\n===== APSK Turbo debug: 32APSK, dualIQ, Turbo 1/2, ', ...
            'random-after, TDL =====\n']);
        fprintf('Seed=%u, SNR=%.1f dB, CFO=%+.1f Hz, phase=%.1f deg, delay=%.3f\n', ...
            uint32(cfg.Seed), cfg.SNR, cfg.CFO, cfg.PhaseOffset, cfg.Delay);
    end
    [M, imagePaths] = run_ccsds_tm_evaluation(p);
end

function cfg = localApplyOptions(cfg, userOpts)
    names = fieldnames(userOpts);
    for k = 1:numel(names)
        name = names{k};
        if ~isfield(cfg, name)
            error('run_tm_apsk_tdl_turbo_debug:UnknownOption', ...
                'Unknown option "%s".', name);
        end
        cfg.(name) = userOpts.(name);
    end
end
