function report = run_tm_data_path_contract_tests(userOpts)
%RUN_TM_DATA_PATH_CONTRACT_TESTS Fast, channel-free dual-I/Q contract tests.
%
% Quick contract and orthogonal generator coverage:
%   report = run_tm_data_path_contract_tests();
%
% Full supported modulation x coding generator matrix, still without a
% channel, synchronization, BER loop, or long frame sweep:
%   report = run_tm_data_path_contract_tests(struct('Profile','full'));
%
% The test proves:
%   1. I1,Q1,I2,Q2 bit packing is exactly reversible.
%   2. Decoded frames merge as I-frame-1,Q-frame-1,...
%   3. A dual-I/Q generator produces the same encoded rails as two fresh
%      single-path generators, then applies the public bit interleave.
%   4. The full profile expands every declared convolutional, LDPC and
%      turbo rate plus every formal RS profile.
%   5. Unsupported capabilities fail at the generator boundary.
%
% It intentionally does not prove RF synchronization, channel performance,
% equalizer performance, or BER thresholds. Use run_tm_data_path_sweep for
% those system-level checks.

    if nargin < 1 || isempty(userOpts)
        userOpts = struct();
    end
    if ~isstruct(userOpts)
        error('run_tm_data_path_contract_tests:InvalidOptions', ...
            'userOpts must be a struct.');
    end

    thisDir = fileparts(mfilename('fullpath'));
    sourceDir = fileparts(thisDir);
    addpath(thisDir);
    addpath(sourceDir);

    opts = struct( ...
        'Profile','quick', ...
        'FailOnFailure',true, ...
        'Verbose',true);
    optionNames = fieldnames(userOpts);
    for k = 1:numel(optionNames)
        name = optionNames{k};
        if ~isfield(opts, name)
            error('run_tm_data_path_contract_tests:UnknownOption', ...
                'Unknown option "%s".', name);
        end
        opts.(name) = userOpts.(name);
    end

    profile = lower(string(opts.Profile));
    if ~isscalar(profile) || ~any(profile == ["helpers","quick","full"])
        error('run_tm_data_path_contract_tests:InvalidProfile', ...
            'Profile must be "helpers", "quick", or "full".');
    end

    capabilities = tm_data_path_capabilities();
    rows = localEmptyRows();

    rows(end+1,1) = localRunCase( ... %#ok<AGROW>
        "contract.bit.hard_round_trip", "bit_contract", "", "", "", false, "", ...
        @localTestHardBitRoundTrip);
    rows(end+1,1) = localRunCase( ... %#ok<AGROW>
        "contract.bit.soft_round_trip", "bit_contract", "", "", "", false, "", ...
        @localTestSoftBitRoundTrip);
    rows(end+1,1) = localRunCase( ... %#ok<AGROW>
        "contract.bit.odd_tail_strict", "bit_contract", "", "", "", false, "", ...
        @localTestOddTailStrict);
    rows(end+1,1) = localRunCase( ... %#ok<AGROW>
        "contract.bit.odd_tail_drop", "bit_contract", "", "", "", false, "", ...
        @localTestOddTailDrop);
    rows(end+1,1) = localRunCase( ... %#ok<AGROW>
        "contract.frame.strict_merge", "frame_contract", "", "", "", false, "", ...
        @localTestStrictFrameMerge);
    rows(end+1,1) = localRunCase( ... %#ok<AGROW>
        "contract.frame.truncate_merge", "frame_contract", "", "", "", false, "", ...
        @localTestTruncatedFrameMerge);
    rows(end+1,1) = localRunCase( ... %#ok<AGROW>
        "contract.catalog.partition", "capability_catalog", "", "", "", false, "", ...
        @() localTestCapabilityPartition(capabilities));

    if profile ~= "helpers"
        generatorCases = localGeneratorCases(capabilities, profile);
        for k = 1:numel(generatorCases)
            c = generatorCases(k);
            caseId = "contract.generator." + lower(c.Modulation) + "." + ...
                lower(c.Coding) + "." + localCaseIdToken(c.Rate) + "." + ...
                lower(c.RandomizerPosition);
            rows(end+1,1) = localRunCase( ...
                caseId, "generator_equivalence", c.Modulation, c.Coding, c.Rate, ...
                c.RandomizerEnabled, c.RandomizerPosition, ...
                @() localTestGeneratorEquivalence(c)); %#ok<AGROW>
        end

        rows(end+1,1) = localRunCase( ... %#ok<AGROW>
            "contract.guard.tpc", "unsupported_guard", "QPSK", "TPC", ...
            "", false, "afterEncoding", @localTestUnsupportedTPC);

        if profile == "full"
            rows(end+1,1) = localRunCase( ... %#ok<AGROW>
                "contract.guard.facm", "unsupported_guard", "FACM", "", ...
                "", false, "afterEncoding", @localTestUnsupportedFACM);
            rows(end+1,1) = localRunCase( ... %#ok<AGROW>
                "contract.guard.ldpc_smtf", "unsupported_guard", "QPSK", ...
                "LDPC-on-SMTF", "1/2", false, "afterEncoding", ...
                @localTestUnsupportedLDPCOnSMTF);
        end
    end

    results = struct2table(rows);
    results.Status = repmat("FAIL", height(results), 1);
    results.Status(results.Pass) = "PASS";
    results = movevars(results, ...
        {'CaseId','Status','Pass','Category','Modulation','Coding','Rate', ...
         'RandomizerEnabled','RandomizerPosition'}, 'Before', 1);

    report = struct();
    report.ContractVersion = capabilities.ContractVersion;
    report.Profile = profile;
    report.Results = results;
    generatorRows = results.Category == "generator_equivalence";
    report.CodingRateCoverage = unique( ...
        results(generatorRows, {'Coding','Rate'}), 'rows', 'stable');
    report.ModulationCapabilities = localModulationCapabilityTable(capabilities);
    report.CodingCapabilities = localCodingCapabilityTable(capabilities);
    report.SeparateWaveformPaths = table( ...
        capabilities.SeparateWaveformPaths(:), ...
        repmat("SEPARATE_PATH", numel(capabilities.SeparateWaveformPaths), 1), ...
        'VariableNames', {'Path','Status'});
    report.Pass = all(results.Pass);

    if opts.Verbose
        fprintf('\nTM dual-I/Q bit contract: profile=%s, PASS=%d/%d\n', ...
            char(profile), nnz(results.Pass), height(results));
        disp(results(:, {'CaseId','Status','Rate','DurationSeconds','Details'}));
        fprintf('\nCoding/rate coverage\n');
        disp(report.CodingRateCoverage);
        fprintf('\nModulation capability catalog\n');
        disp(report.ModulationCapabilities);
        fprintf('\nCoding capability catalog\n');
        disp(report.CodingCapabilities);
    end

    if opts.FailOnFailure && ~report.Pass
        failedIds = strjoin(results.CaseId(~results.Pass), ', ');
        error('run_tm_data_path_contract_tests:Failed', ...
            'TM dual-I/Q contract failed: %s', char(failedIds));
    end
end

function rows = localEmptyRows()
    rows = struct( ...
        'CaseId',{}, ...
        'Category',{}, ...
        'Modulation',{}, ...
        'Coding',{}, ...
        'Rate',{}, ...
        'RandomizerEnabled',{}, ...
        'RandomizerPosition',{}, ...
        'Pass',{}, ...
        'DurationSeconds',{}, ...
        'Details',{});
end

function row = localRunCase(caseId, category, modulation, coding, rate, ...
        randomizerEnabled, randomizerPosition, testFunction)
    started = tic;
    passed = false;
    try
        details = string(testFunction());
        passed = true;
    catch exception
        details = string(exception.identifier) + ": " + string(exception.message);
    end
    row = struct( ...
        'CaseId',string(caseId), ...
        'Category',string(category), ...
        'Modulation',string(modulation), ...
        'Coding',string(coding), ...
        'Rate',string(rate), ...
        'RandomizerEnabled',logical(randomizerEnabled), ...
        'RandomizerPosition',string(randomizerPosition), ...
        'Pass',passed, ...
        'DurationSeconds',toc(started), ...
        'Details',details);
end

function details = localTestHardBitRoundTrip()
    bitsI = int8([0;1;1;0;1;0]);
    bitsQ = int8([1;0;1;0;0;1]);
    expected = int8([0;1;1;0;1;1;0;0;1;0;0;1]);
    packed = tm_data_path_bit_interleave(bitsI, bitsQ);
    localRequire(isequal(packed, expected), ...
        'Hard-bit packed order is not I1,Q1,I2,Q2,...');
    [actualI, actualQ] = tm_data_path_bit_deinterleave(packed);
    localRequire(isequal(actualI, bitsI) && isequal(actualQ, bitsQ), ...
        'Hard-bit I/Q round trip changed a rail.');
    details = "exact int8 pack/unpack";
end

function details = localTestSoftBitRoundTrip()
    softI = [-3.5;0.25;7.0;-0.125];
    softQ = [4.0;-1.5;0.75;2.25];
    packed = tm_data_path_bit_interleave(softI, softQ);
    [actualI, actualQ] = tm_data_path_bit_deinterleave(packed);
    localRequire(isequal(actualI, softI) && isequal(actualQ, softQ), ...
        'Soft-value I/Q round trip changed a rail.');
    details = "exact double-valued pack/unpack";
end

function details = localTestOddTailStrict()
    localAssertThrows(@() tm_data_path_bit_deinterleave(int8([0;1;1])), ...
        'tm_data_path_bit_deinterleave:OddLength');
    details = "strict mode rejects an unpaired tail";
end

function details = localTestOddTailDrop()
    [bitsI, bitsQ, dropped] = ...
        tm_data_path_bit_deinterleave(int8([0;1;1]), 'drop');
    localRequire(dropped && isequal(bitsI, int8(0)) && isequal(bitsQ, int8(1)), ...
        'Drop mode did not remove exactly one unpaired tail value.');
    details = "receiver tolerance drops exactly one tail";
end

function details = localTestStrictFrameMerge()
    bitsI = int16([1;2;3;4;5;6]);
    bitsQ = int16([11;12;13;14;15;16]);
    actual = tm_data_path_frame_interleave(bitsI, bitsQ, 3);
    expected = int16([1;2;3;11;12;13;4;5;6;14;15;16]);
    localRequire(isequal(actual, expected), ...
        'Decoded frame order is not I1,Q1,I2,Q2,...');
    details = "two 3-value frames merged in rail order";
end

function details = localTestTruncatedFrameMerge()
    bitsI = int8([1;2;3;4;5;6;7]);
    bitsQ = int8([11;12;13;14;15;16]);
    localAssertThrows( ...
        @() tm_data_path_frame_interleave(bitsI, bitsQ, 3), ...
        'tm_data_path_frame_interleave:IncompleteFrames');
    actual = tm_data_path_frame_interleave(bitsI, bitsQ, 3, 'truncate');
    expected = int8([1;2;3;11;12;13;4;5;6;14;15;16]);
    localRequire(isequal(actual, expected), ...
        'Truncate mode did not keep exactly the common complete frames.');
    details = "strict rejects partial frame; RX mode truncates it";
end

function details = localTestCapabilityPartition(capabilities)
    modulationGroups = { ...
        capabilities.SupportedModulations, ...
        capabilities.AddNextModulations, ...
        capabilities.SeparateDesignModulations, ...
        capabilities.NotApplicableModulations};
    codingGroups = { ...
        capabilities.SupportedCodings, ...
        capabilities.AddNextCodings};
    localRequire(localIsUniquePartition(modulationGroups), ...
        'A modulation appears in more than one capability category.');
    localRequire(localIsUniquePartition(codingGroups), ...
        'A coding appears in more than one capability category.');
    localRequire(numel(capabilities.AllOrdinaryTMModulations) == 14, ...
        'Ordinary-TM modulation catalog must classify all 14 current modes.');
    localRequire(numel(capabilities.AllOrdinaryTMCodings) == 7, ...
        'Ordinary-TM coding catalog must classify all 7 current modes.');
    details = "14 modulations and 7 codings classified once";
end

function tf = localIsUniquePartition(groups)
    allValues = strings(0,1);
    for k = 1:numel(groups)
        allValues = [allValues; lower(groups{k}(:))]; %#ok<AGROW>
    end
    tf = numel(unique(allValues)) == numel(allValues);
end

function cases = localGeneratorCases(capabilities, profile)
    cases = struct( ...
        'Modulation',{}, ...
        'Coding',{}, ...
        'Rate',{}, ...
        'Extra',{}, ...
        'RandomizerEnabled',{}, ...
        'RandomizerPosition',{});
    allCodingProfiles = localCodingProfiles(capabilities);
    defaultCodingProfiles = localDefaultCodingProfiles(allCodingProfiles);

    if profile == "full"
        for iMod = 1:numel(capabilities.SupportedModulations)
            for iCode = 1:numel(allCodingProfiles)
                cases(end+1,1) = localGeneratorCase( ...
                    capabilities.SupportedModulations(iMod), ...
                    allCodingProfiles(iCode), false, "off"); %#ok<AGROW>
            end
        end
    else
        noCoding = allCodingProfiles(strcmpi( ...
            string({allCodingProfiles.Coding}), "none"));
        for iMod = 1:numel(capabilities.SupportedModulations)
            cases(end+1,1) = localGeneratorCase( ...
                capabilities.SupportedModulations(iMod), ...
                noCoding, false, "off"); %#ok<AGROW>
        end
        for iCode = 1:numel(defaultCodingProfiles)
            codingProfile = defaultCodingProfiles(iCode);
            if ~strcmpi(codingProfile.Coding, "none")
                cases(end+1,1) = localGeneratorCase( ...
                    "QPSK", codingProfile, false, "off"); %#ok<AGROW>
            end
        end
    end

    if profile == "full"
        randomizedProfiles = allCodingProfiles;
    else
        randomizedProfiles = defaultCodingProfiles(strcmpi( ...
            string({defaultCodingProfiles.Coding}), "convolutional"));
    end
    randomizedModulations = ["QPSK","16APSK","32APSK"];
    for iMod = 1:numel(randomizedModulations)
        for iCode = 1:numel(randomizedProfiles)
            codingProfile = randomizedProfiles(iCode);
            cases(end+1,1) = localGeneratorCase( ...
                randomizedModulations(iMod), codingProfile, ...
                true, "beforeEncoding"); %#ok<AGROW>
            cases(end+1,1) = localGeneratorCase( ...
                randomizedModulations(iMod), codingProfile, ...
                true, "afterEncoding"); %#ok<AGROW>
        end
    end
end

function profiles = localCodingProfiles(capabilities)
    profiles = struct('Coding',{},'Rate',{},'Extra',{});
    profiles(end+1,1) = localCodingProfile( ... %#ok<AGROW>
        "none", "-", struct('NumBytesInTransferFrame',26));

    rsProfiles = capabilities.SupportedRSProfiles;
    for k = 1:numel(rsProfiles)
        rs = rsProfiles(k);
        rsExtra = struct( ...
            'RSMessageLength', double(rs.RSMessageLength), ...
            'RSInterleavingDepth', double(rs.RSInterleavingDepth), ...
            'IsRSMessageShortened', logical(rs.IsRSMessageShortened));
        if rs.IsRSMessageShortened
            rsExtra.RSShortenedMessageLength = ...
                double(rs.RSShortenedMessageLength);
        end
        profiles(end+1,1) = localCodingProfile( ... %#ok<AGROW>
            "RS", rs.Rate, rsExtra);
    end

    for rate = capabilities.SupportedConvolutionalRates
        profiles(end+1,1) = localCodingProfile( ... %#ok<AGROW>
            "convolutional", rate, struct( ...
                'NumBytesInTransferFrame', localConvolutionalFrameBytes(rate), ...
                'ConvolutionalCodeRate', char(rate)));
    end
    for rate = capabilities.SupportedLDPCRates
        profiles(end+1,1) = localCodingProfile( ... %#ok<AGROW>
            "LDPC", rate, struct( ...
                'CodeRate', char(rate), ...
                'NumBitsInInformationBlock', 1024, ...
                'IsLDPCOnSMTF', false));
    end
    for rate = capabilities.SupportedTurboRates
        profiles(end+1,1) = localCodingProfile( ... %#ok<AGROW>
            "turbo", rate, struct( ...
                'CodeRate', char(rate), ...
                'NumBitsInInformationBlock', 1784));
    end
end

function profiles = localDefaultCodingProfiles(allProfiles)
    keep = false(size(allProfiles));
    for k = 1:numel(allProfiles)
        coding = string(allProfiles(k).Coding);
        rate = string(allProfiles(k).Rate);
        keep(k) = coding == "none" || ...
            (coding == "RS" && rate == "223/255") || ...
            (coding == "convolutional" && rate == "1/2") || ...
            (coding == "LDPC" && rate == "1/2") || ...
            (coding == "turbo" && rate == "1/2");
    end
    profiles = allProfiles(keep);
end

function profile = localCodingProfile(coding, rate, extra)
    profile = struct( ...
        'Coding',char(coding), ...
        'Rate',string(rate), ...
        'Extra',extra);
end

function frameBytes = localConvolutionalFrameBytes(rate)
    % Select short frames whose ASM+TF coded length is divisible by every
    % currently supported split modulation order (2, 3, 4 and 5 bits/sym).
    switch char(rate)
        case {'1/2','2/3'}
            frameBytes = 26;
        case '3/4'
            frameBytes = 41;
        case '5/6'
            frameBytes = 46;
        case '7/8'
            frameBytes = 101;
        otherwise
            error('run_tm_data_path_contract_tests:UnknownConvolutionalRate', ...
                'No aligned contract frame length for rate "%s".', rate);
    end
end

function c = localGeneratorCase(modulation, codingProfile, enabled, position)
    c = struct( ...
        'Modulation',string(modulation), ...
        'Coding',string(codingProfile.Coding), ...
        'Rate',string(codingProfile.Rate), ...
        'Extra',codingProfile.Extra, ...
        'RandomizerEnabled',logical(enabled), ...
        'RandomizerPosition',string(position));
end

function token = localCaseIdToken(value)
    token = lower(string(value));
    token = regexprep(token, '[^a-zA-Z0-9]+', '_');
    token = regexprep(token, '^_+|_+$', '');
    if strlength(token) == 0
        token = "none";
    end
end

function details = localTestGeneratorEquivalence(testCase)
    position = testCase.RandomizerPosition;
    if ~testCase.RandomizerEnabled
        position = "afterEncoding";
    end
    dualArgs = localGeneratorArgs(testCase.Modulation, testCase.Coding, ...
        testCase.Extra, "dualIQ", testCase.RandomizerEnabled, position);
    singleArgs = localGeneratorArgs(testCase.Modulation, testCase.Coding, ...
        testCase.Extra, "single", testCase.RandomizerEnabled, position);

    dualGenerator = ccsdsTMWaveformGenerator(dualArgs{:});
    singleGeneratorI = ccsdsTMWaveformGenerator(singleArgs{:});
    singleGeneratorQ = ccsdsTMWaveformGenerator(singleArgs{:});

    railLength = dualGenerator.NumInputBits/2;
    localRequire(railLength == singleGeneratorI.NumInputBits, ...
        'dualIQ NumInputBits is not exactly two single-path frames.');
    index = (0:railLength-1).';
    messageI = int8(mod(index + floor(index/7), 2));
    messageQ = int8(mod(floor(index/3) + floor(index/11) + 1, 2));
    localRequire(~isequal(messageI, messageQ), ...
        'Test rail tags must be different.');

    [~, dualEncoded] = dualGenerator([messageI;messageQ]);
    [~, encodedI] = singleGeneratorI(messageI);
    [~, encodedQ] = singleGeneratorQ(messageQ);
    expected = tm_data_path_bit_interleave(int8(encodedI), int8(encodedQ));

    localRequire(isequal(int8(dualEncoded), expected), ...
        ['dualIQ encoded output differs from two independently encoded ', ...
         'single rails followed by I/Q interleave.']);
    [roundTripI, roundTripQ] = ...
        tm_data_path_bit_deinterleave(int8(dualEncoded));
    localRequire(isequal(roundTripI, int8(encodedI)) && ...
        isequal(roundTripQ, int8(encodedQ)), ...
        'Encoded rail tags did not survive deinterleave.');

    dualInfo = info(dualGenerator);
    details = sprintf('rate=%s actual=%.9g, %d input bits/rail -> %d encoded bits/rail', ...
        char(testCase.Rate), dualInfo.ActualCodeRate, ...
        railLength, numel(encodedI));
end

function args = localGeneratorArgs(modulation, coding, extra, dataPathMode, ...
        randomizerEnabled, randomizerPosition)
    args = { ...
        'WaveformSource','synchronization and channel coding', ...
        'ChannelCoding',char(coding), ...
        'Modulation',char(modulation), ...
        'DataPathMode',char(dataPathMode), ...
        'RandomizerEnabled',logical(randomizerEnabled), ...
        'RandomizerFECPosition',char(randomizerPosition), ...
        'HasASM',true};

    names = fieldnames(extra);
    for k = 1:numel(names)
        args = [args, {names{k}, extra.(names{k})}]; %#ok<AGROW>
    end
end

function details = localTestUnsupportedModulation(modulation)
    args = localGeneratorArgs(modulation, "none", ...
        struct('NumBytesInTransferFrame',26), "dualIQ", ...
        false, "afterEncoding");
    localAssertGeneratorRejected(args, ...
        'ccsdsTMWaveformGenerator:SplitUnsupportedModulation');
    details = modulation + " is cataloged but not silently enabled";
end

function details = localTestUnsupportedTPC()
    args = { ...
        'WaveformSource','synchronization and channel coding', ...
        'ChannelCoding','TPC', ...
        'Modulation','QPSK', ...
        'DataPathMode','dualIQ', ...
        'RandomizerEnabled',false, ...
        'HasASM',true, ...
        'TPCCodeRate','56', ...
        'TPCBlocksPerTF',1, ...
        'TPCInterleaver','auto'};
    localAssertGeneratorRejected(args, ...
        'ccsdsTMWaveformGenerator:SplitUnsupportedCoding');
    details = "TPC remains explicitly blocked pending dual-rail enablement";
end

function details = localTestUnsupportedFACM()
    args = { ...
        'WaveformSource','flexible advanced coding and modulation', ...
        'ACMFormat',14, ...
        'NumBytesInTransferFrame',223, ...
        'DataPathMode','dualIQ'};
    localAssertGeneratorRejected(args, ...
        'ccsdsTMWaveformGenerator:SplitUnsupported');
    details = "FACM remains a separate waveform path";
end

function details = localTestUnsupportedLDPCOnSMTF()
    args = { ...
        'WaveformSource','synchronization and channel coding', ...
        'ChannelCoding','LDPC', ...
        'Modulation','QPSK', ...
        'CodeRate','1/2', ...
        'NumBitsInInformationBlock',1024, ...
        'IsLDPCOnSMTF',true, ...
        'LDPCCodeblockSize',1, ...
        'NumBytesInTransferFrame',128, ...
        'DataPathMode','dualIQ'};
    localAssertGeneratorRejected(args, ...
        'ccsdsTMWaveformGenerator:SplitUnsupported');
    details = "LDPC-on-SMTF remains a separate framing path";
end

function localAssertGeneratorRejected(args, expectedIdentifier)
    warningState = warning('query', 'MATLAB:system:nonRelevantProperty');
    warningCleanup = onCleanup(@() warning(warningState));
    warning('off', 'MATLAB:system:nonRelevantProperty');
    generator = ccsdsTMWaveformGenerator(args{:});
    input = zeros(generator.NumInputBits, 1, 'int8');
    localAssertThrows(@() generator(input), expectedIdentifier);
    clear warningCleanup;
end

function tableValue = localModulationCapabilityTable(capabilities)
    modulation = [ ...
        capabilities.SupportedModulations(:); ...
        capabilities.AddNextModulations(:); ...
        capabilities.SeparateDesignModulations(:); ...
        capabilities.NotApplicableModulations(:)];
    status = [ ...
        repmat("SUPPORTED", numel(capabilities.SupportedModulations), 1); ...
        repmat("ADD_NEXT", numel(capabilities.AddNextModulations), 1); ...
        repmat("SEPARATE_DESIGN", numel(capabilities.SeparateDesignModulations), 1); ...
        repmat("NOT_APPLICABLE", numel(capabilities.NotApplicableModulations), 1)];
    reason = strings(numel(modulation),1);
    reason(status == "SUPPORTED") = ...
        "current equal-rail ordinary-TM implementation";
    reason(modulation == "16APSK" | modulation == "32APSK") = ...
        "ordinary-TM APSK with independent rail coding/randomization and split receiver";
    reason(modulation == "UQPSK") = ...
        "uses separate experimental unequalDualIQ; not equal-rail dualIQ";
    reason(modulation == "4D-8PSK-TCM") = ...
        "grouped trellis state requires a separate rail design";
    reason(status == "NOT_APPLICABLE") = ...
        "one-bit/symbol or special waveform has no independent I/Q bit positions";
    tableValue = table(modulation, status, reason, ...
        'VariableNames', {'Modulation','Status','Reason'});
end

function tableValue = localCodingCapabilityTable(capabilities)
    coding = [ ...
        capabilities.SupportedCodings(:); ...
        capabilities.AddNextCodings(:)];
    status = [ ...
        repmat("SUPPORTED", numel(capabilities.SupportedCodings), 1); ...
        repmat("ADD_NEXT", numel(capabilities.AddNextCodings), 1)];
    reason = strings(numel(coding),1);
    reason(status == "SUPPORTED") = ...
        "current independent per-rail encoder/decoder path";
    reason(coding == "TPC") = ...
        "block-stateless implementation; best next coding candidate";
    reason(coding == "concatenated") = ...
        "requires independent per-rail convolutional buffers and differential state";
    tableValue = table(coding, status, reason, ...
        'VariableNames', {'Coding','Status','Reason'});
end

function localAssertThrows(functionHandle, expectedIdentifier)
    try
        functionHandle();
    catch exception
        localRequire(strcmp(exception.identifier, expectedIdentifier), ...
            sprintf('Expected error "%s", got "%s": %s', ...
                expectedIdentifier, exception.identifier, exception.message));
        return;
    end
    error('run_tm_data_path_contract_tests:ExpectedErrorNotThrown', ...
        'Expected error "%s" was not thrown.', expectedIdentifier);
end

function localRequire(condition, message)
    if ~condition
        error('run_tm_data_path_contract_tests:ContractViolation', '%s', message);
    end
end
