function T = run_tm_release_matrix_json(userOpts)
%RUN_TM_RELEASE_MATRIX_JSON Capability-driven ordinary-TM release matrix.
%
% This entry point keeps the old sweep runners untouched and builds only
% combinations that are valid for the selected data path:
%   single         : BPSK/QPSK/OQPSK/8PSK/16QAM/32QAM/MSK/GMSK
%   dualIQ         : QPSK/OQPSK/8PSK/16QAM/32QAM/16APSK/32APSK
%   unequalDualIQ  : UQPSK only
%
% It expands RS, all supported convolutional/LDPC/Turbo rates, and the
% off/after/before randomizer modes.  Results are checkpointed by
% reg_run_cases and exported as a metrics-only JSON summary.
%
% Example:
%   opts = struct('Profile','h-functional', ...
%       'SymbolRate',20e6,'SamplesPerSymbol',8,'BERFrames',16);
%   T = run_tm_release_matrix_json(opts);

    if nargin < 1 || isempty(userOpts)
        userOpts = struct();
    end
    if ~isstruct(userOpts)
        error('run_tm_release_matrix_json:InvalidOptions', ...
            'userOpts must be a struct.');
    end

    thisDir = fileparts(mfilename('fullpath'));
    srcDir = fileparts(thisDir);
    addpath(thisDir, '-begin');
    addpath(srcDir);

    profile = string(localOption(userOpts, 'Profile', "h-functional"));
    cfg = localDefaults(profile);
    cfg = localMergeOptions(cfg, userOpts);
    cfg.Profile = lower(string(cfg.Profile));

    [cases, plan] = localBuildCases(cfg);
    fprintf('\n===== TM release matrix plan =====\n');
    fprintf('Profile: %s\n', char(cfg.Profile));
    fprintf('Cases: %d\n', numel(cases));
    fprintf('Paths: single=%d dualIQ=%d unequalDualIQ=%d\n', ...
        plan.Single, plan.DualIQ, plan.UnequalDualIQ);
    fprintf('Channels: noH=%d H=%d | codings=%d | randomizers=%d\n', ...
        plan.NoHChannels, plan.HChannels, plan.Codings, plan.Randomizers);

    runnerOpts = struct( ...
        'OutputDir', cfg.OutputDir, ...
        'RunId', cfg.RunId, ...
        'PlanVersion', "tm-release-matrix-v1-" + cfg.Profile, ...
        'Resume', cfg.Resume, ...
        'MaxNewCases', cfg.MaxNewCases, ...
        'RerunFailed', cfg.RerunFailed, ...
        'BaseSeed', cfg.BaseSeed, ...
        'SeedMode', cfg.SeedMode, ...
        'CaseIds', cfg.CaseIds, ...
        'DryRun', cfg.DryRun, ...
        'FailOnFailure', cfg.FailOnFailure, ...
        'Verbose', cfg.Verbose);

    [T, state] = reg_run_cases("tm_release_matrix", cases, runnerOpts);
    T = localAttachMetadata(T, cases, cfg);

    if ~cfg.DryRun
        outputDir = char(state.OutputDir);
        csvPath = fullfile(outputDir, 'tm_release_matrix_summary.csv');
        jsonPath = fullfile(outputDir, 'tm_release_matrix_summary.json');
        localWriteTable(T, csvPath);
        localWriteJson(T, cfg, plan, jsonPath);

        fprintf('\n===== TM release matrix result =====\n');
        fprintf('Total=%d FunctionalPass=%d PerformancePass=%d ERROR=%d\n', ...
            height(T), nnz(T.FunctionalPass), nnz(T.PerformancePass), ...
            nnz(T.Status == "ERROR"));
        fprintf('Checkpoint: %s\n', fullfile(outputDir, 'checkpoint.mat'));
        fprintf('CSV       : %s\n', csvPath);
        fprintf('JSON      : %s\n', jsonPath);
    end
end

function cfg = localDefaults(profile)
    channelDir = 'E:/matlab_project/v3.0/v3.0/channel';
    hCases = { ...
        'default_ChannelData', fullfile(channelDir, 'ChannelData.mat'); ...
        'std2_likely_TDL',      fullfile(channelDir, '2-ChannelData.mat'); ...
        'std3_likely_CDL',      fullfile(channelDir, '3-ChannelData.mat'); ...
        'std4_likely_ITU_P681', fullfile(channelDir, '4-ChannelData.mat'); ...
        'std5_likely_Jakes',    fullfile(channelDir, 'ChannelData_5.mat'); ...
        'std6_likely_CLoo',     fullfile(channelDir, 'ChannelData_6.mat'); ...
        'std7_likely_Corazza',  fullfile(channelDir, 'ChannelData_7.mat'); ...
        'std8_likely_Lutz',     fullfile(channelDir, 'ChannelData_8.mat')};

    % The official frame-reset/Viterbi receiver is required for coded GMSK
    % (especially Turbo/LDPC). legacy-diff remains available as an explicit
    % diagnostic override in run_ccsds_tm_evaluation.
    cfg = struct( ...
        'Profile', profile, ...
        'OutputDir', '', ...
        'RunId', ['tm_release_' char(profile) '_' datestr(now,'yyyymmdd_HHMMSS')], ...
        'Resume', true, ...
        'MaxNewCases', Inf, ...
        'RerunFailed', false, ...
        'BaseSeed', 20260804, ...
        'SeedMode', 'pairedChannelProfile', ...
        'CaseIds', strings(0,1), ...
        'DryRun', false, ...
        'FailOnFailure', false, ...
        'Verbose', true, ...
        'IncludeNoH', true, ...
        'IncludeH', true, ...
        'HModelCases', {hCases}, ...
        'IncludeSinglePath', true, ...
        'IncludeDualIQPath', true, ...
        'IncludeUnequalUQPSK', true, ...
        'SingleModulations', {{'BPSK','QPSK','OQPSK','8PSK', ...
                               '16QAM','32QAM','MSK','GMSK'}}, ...
        'DualIQModulations', {{'QPSK','OQPSK','8PSK','16QAM','32QAM', ...
                               '16APSK','32APSK'}}, ...
        'IncludeUncoded', true, ...
        'IncludeRS', true, ...
        'IncludeConvolutional', true, ...
        'IncludeLDPC', true, ...
        'IncludeTurbo', true, ...
        'ConvolutionalRates', {{'1/2','2/3','3/4','5/6','7/8'}}, ...
        'LDPCRates', {{'1/2','2/3','4/5'}}, ...
        'TurboRates', {{'1/2','1/3','1/4','1/6'}}, ...
        'RandomizerCases', localRandomizers(), ...
        'SymbolRate', 1e6, ...
        'SamplesPerSymbol', 8, ...
        'RolloffFactor', 0.35, ...
        'SNR', 40, ...
        'CFO', 0, ...
        'PhaseOffset', 0, ...
        'Delay', 0, ...
        'NoisePlacement', 'afterChannel', ...
        'ChannelInterpolationMethod', 'linear', ...
        'ChannelOutOfRangeMode', 'wrap', ...
        'InterpolateChannelDelays', false, ...
        'NormalizeHChannel', false, ...
        'EqualizerMode', 'mmse', ...
        'EqualizerReg', [], ...
        'NormalizeEqualizerOutput', true, ...
        'AGCEnabled', false, ...
        'AGCTimeConstantMs', 10, ...
        'AdaptiveEqualizerTaps', 11, ...
        'AdaptiveEqualizerCMAStep', 0.01, ...
        'AdaptiveEqualizerDDStep', 1e-3, ...
        'AdaptiveEqualizerCMAWarmupSymbols', 2000, ...
        'AdaptiveEqualizerDDPasses', 1, ...
        'AdaptiveEqualizerDecisionGate', [], ...
        'AdaptiveEqualizerMaxTapNorm', 4, ...
        'AdaptiveEqualizerCMASwitchMSE', [], ...
        'AdaptiveEqualizerMinCMAConfidence', 0.50, ...
        'AdaptiveEqualizerRequireCMAConvergence', true, ...
        'AdaptiveEqualizerQualityGuard', true, ...
        'AdaptiveEqualizerMaxMSEDegradation', 0.10, ...
        'AdaptiveEqualizerMSEDegradationMargin', 1e-3, ...
        'AdaptiveEqualizerScalarSideTapOnRatio', 0.02, ...
        'AdaptiveEqualizerDDWindowSymbols', 256, ...
        'AdaptiveEqualizerDDMinWindowAcceptance', 0.75, ...
        'AdaptiveEqualizerScalarDDPasses', -1, ...
        'AdaptiveEqualizerEnableFadeHold', true, ...
        'AdaptiveEqualizerEnableQAMWindowHold', false, ...
        'AdaptiveEqualizerAutoScalarForQAM', false, ...
        'BERWarmUpFrames', 8, ...
        'BERFrames', 16, ...
        'MaxBER', 1e-5, ...
        'MinLockRate', 0.90, ...
        'MaxFER', 1e-5, ...
        'GMSKDetectionMode', 'official-viterbi-frame-reset', ...
        'GMSKBT', 0.5, ...
        'UseTMAPSKPilots', true, ...
        'TMAPSKPilotInterval', 512, ...
        'TMAPSKPilotLength', 32, ...
        'TMAPSKPilotPreambleLength', 64, ...
        'TMAPSKPilotCorrectionMode', 'mmseinterp', ...
        'TMAPSKPilotPhaseSmoothWindow', 3, ...
        'TMAPSKPilotMMSERegularization', 0.01, ...
        'TMAPSKPilotMaxGainDB', 18, ...
        'TMAPSKPilotFadeThresholdDB', -12, ...
        'TMAPSKPilotFadeHold', true, ...
        'HasFECF', false, ...
        'CRCType', 'CCITT', ...
        'FrameSyncBitSlipTolerance', 3, ...
        'FrameSyncASMErrorThreshold', 3, ...
        'FrameSyncLockThreshold', 2, ...
        'FrameSyncUnlockThreshold', 3, ...
        'MSKCoarseCFO', false, ...
        'Debug', false, ...
        'DebugPerFrameBERSummary', false);

    switch lower(string(profile))
        case "noh-functional"
            cfg.IncludeH = false;
            cfg.SNR = 100;
            cfg.CFO = 0;
            cfg.PhaseOffset = 0;
            cfg.Delay = 0;
        case "h-functional"
            cfg.SNR = 65;
            cfg.CFO = 0;
            cfg.PhaseOffset = 0;
            cfg.Delay = 0;
        case "performance"
            cfg.SNR = 35;
            cfg.CFO = 20000;
            cfg.PhaseOffset = 10;
            cfg.Delay = 0.2;
            cfg.MaxBER = 1e-3;
            cfg.MaxFER = [];
        case "custom"
            % Keep all values supplied by the caller.
        otherwise
            error('run_tm_release_matrix_json:UnknownProfile', ...
                'Profile must be noh-functional, h-functional, performance, or custom.');
    end
end

function cfg = localMergeOptions(cfg, userOpts)
    names = fieldnames(userOpts);
    for k = 1:numel(names)
        if ~isfield(cfg, names{k})
            error('run_tm_release_matrix_json:UnknownOption', ...
                'Unknown option "%s".', names{k});
        end
        cfg.(names{k}) = userOpts.(names{k});
    end
    if isempty(cfg.OutputDir)
        cfg.OutputDir = fullfile( ...
            'E:/web_code/react/fft_project/react-fft/artifacts/ccsds/tm_release', ...
            char(cfg.RunId));
    end
    cfg.OutputDir = char(cfg.OutputDir);
    cfg.Profile = lower(string(cfg.Profile));
    cfg.SeedMode = char(string(cfg.SeedMode));
    cfg.Resume = logical(cfg.Resume);
    cfg.RerunFailed = logical(cfg.RerunFailed);
    cfg.DryRun = logical(cfg.DryRun);
    cfg.FailOnFailure = logical(cfg.FailOnFailure);
    cfg.Verbose = logical(cfg.Verbose);
end

function [cases, plan] = localBuildCases(cfg)
    cases = localEmptyCases();
    plan = struct('Single',0,'DualIQ',0,'UnequalDualIQ',0, ...
        'NoHChannels',0,'HChannels',0,'Codings',0,'Randomizers',0);

    channels = localBuildChannels(cfg);
    codings = localBuildCodings(cfg);
    randomizers = cfg.RandomizerCases;
    plan.NoHChannels = nnz(~[channels.HEnabled]);
    plan.HChannels = nnz([channels.HEnabled]);
    plan.Codings = numel(codings);
    plan.Randomizers = numel(randomizers);

    for ich = 1:numel(channels)
        channel = channels(ich);

        if cfg.IncludeSinglePath
            mods = localCellstr(cfg.SingleModulations);
            for im = 1:numel(mods)
                for ic = 1:numel(codings)
                    for ir = 1:numel(randomizers)
                        cases(end+1,1) = localMakeCase(cfg, channel, ...
                            'single', mods{im}, codings(ic), randomizers(ir)); %#ok<AGROW>
                        plan.Single = plan.Single + 1;
                    end
                end
            end
        end

        if cfg.IncludeDualIQPath
            mods = localCellstr(cfg.DualIQModulations);
            for im = 1:numel(mods)
                for ic = 1:numel(codings)
                    for ir = 1:numel(randomizers)
                        cases(end+1,1) = localMakeCase(cfg, channel, ...
                            'dualIQ', mods{im}, codings(ic), randomizers(ir)); %#ok<AGROW>
                        plan.DualIQ = plan.DualIQ + 1;
                    end
                end
            end
        end

        if cfg.IncludeUnequalUQPSK
            for ic = 1:numel(codings)
                for ir = 1:numel(randomizers)
                    cases(end+1,1) = localMakeCase(cfg, channel, ...
                        'unequalDualIQ', 'UQPSK', codings(ic), randomizers(ir)); %#ok<AGROW>
                    plan.UnequalDualIQ = plan.UnequalDualIQ + 1;
                end
            end
        end
    end
end

function channels = localBuildChannels(cfg)
    channels = struct('Name',{},'HEnabled',{},'File',{});
    if cfg.IncludeNoH
        channels(end+1) = struct('Name','noH','HEnabled',false,'File',''); %#ok<AGROW>
    end
    if cfg.IncludeH
        hCases = cfg.HModelCases;
        if iscell(hCases) && size(hCases,2) ~= 2
            error('run_tm_release_matrix_json:InvalidHModelCases', ...
                'HModelCases must be an N-by-2 cell array: {label, file}.');
        end
        for k = 1:size(hCases,1)
            label = char(string(hCases{k,1}));
            filePath = char(string(hCases{k,2}));
            if exist(filePath,'file') ~= 2
                error('run_tm_release_matrix_json:MissingHFile', ...
                    'H file does not exist: %s', filePath);
            end
            channels(end+1) = struct('Name',label, ...
                'HEnabled',true,'File',filePath); %#ok<AGROW>
        end
    end
end

function codings = localBuildCodings(cfg)
    codings = struct('Coding',{},'Rate',{},'TFBytes',{},'Extra',{});
    if cfg.IncludeUncoded
        codings(end+1) = localCoding('none','-',1115,struct()); %#ok<AGROW>
    end
    if cfg.IncludeRS
        codings(end+1) = localCoding('RS','223/255',1115,struct( ...
            'RSMessageLength',223,'RSInterleavingDepth',1, ...
            'IsRSMessageShortened',false)); %#ok<AGROW>
    end
    if cfg.IncludeConvolutional
        rates = localCellstr(cfg.ConvolutionalRates);
        for k = 1:numel(rates)
            rate = rates{k};
            tfBytes = 1115;
            if strcmp(rate,'5/6'), tfBytes = 1116; end
            if strcmp(rate,'7/8'), tfBytes = 1123; end
            codings(end+1) = localCoding('convolutional',rate,tfBytes, ...
                struct('ConvolutionalCodeRate',rate)); %#ok<AGROW>
        end
    end
    if cfg.IncludeLDPC
        rates = localCellstr(cfg.LDPCRates);
        for k = 1:numel(rates)
            rate = rates{k};
            codings(end+1) = localCoding('LDPC',rate,1115,struct( ...
                'CodeRate',rate,'NumBitsInInformationBlock',1024, ...
                'IsLDPCOnSMTF',false)); %#ok<AGROW>
        end
    end
    if cfg.IncludeTurbo
        rates = localCellstr(cfg.TurboRates);
        for k = 1:numel(rates)
            rate = rates{k};
            codings(end+1) = localCoding('turbo',rate,1115,struct( ...
                'CodeRate',rate,'NumBitsInInformationBlock',1784)); %#ok<AGROW>
        end
    end
end

function c = localCoding(coding, rate, tfBytes, extra)
    c = struct('Coding',char(coding),'Rate',char(rate), ...
        'TFBytes',double(tfBytes),'Extra',extra);
end

function randomizers = localRandomizers()
    randomizers = struct('Label',{},'Enabled',{},'Position',{});
    randomizers(end+1) = struct('Label','off','Enabled',false, ...
        'Position','afterEncoding'); %#ok<AGROW>
    randomizers(end+1) = struct('Label','after','Enabled',true, ...
        'Position','afterEncoding'); %#ok<AGROW>
    randomizers(end+1) = struct('Label','before','Enabled',true, ...
        'Position','beforeEncoding'); %#ok<AGROW>
end

function caseDef = localMakeCase(cfg, channel, pathMode, modulation, coding, randomizer)
    p = struct( ...
        'modType',modulation, ...
        'DataPathMode',pathMode, ...
        'WaveformMode','ordinaryTM', ...
        'symbolRate',cfg.SymbolRate, ...
        'sps',cfg.SamplesPerSymbol, ...
        'snr',cfg.SNR, ...
        'cfo',cfg.CFO, ...
        'phaseOffset',cfg.PhaseOffset, ...
        'delay',cfg.Delay, ...
        'noisePlacement',cfg.NoisePlacement, ...
        'RolloffFactor',cfg.RolloffFactor, ...
        'channelCoding',coding.Coding, ...
        'NumBytesInTransferFrame',coding.TFBytes, ...
        'RandomizerEnabled',logical(randomizer.Enabled), ...
        'RandomizerFECPosition',randomizer.Position, ...
        'hasASM',true, ...
        'berWarmUpFrames',cfg.BERWarmUpFrames, ...
        'berFrames',cfg.BERFrames, ...
        'showFigures',false, ...
        'splitPathDebug',logical(cfg.Debug), ...
        'UseSplitReceiverCoordinator',true, ...
        'splitIQPhaseTwoPass',false, ...
        'enableCodedPhaseSearch',false, ...
        'enableHChannel',logical(channel.HEnabled), ...
        'enableEqualizer',logical(channel.HEnabled), ...
        'normalizeHChannel',logical(cfg.NormalizeHChannel), ...
        'normalizeEqualizerOutput',logical(cfg.NormalizeEqualizerOutput), ...
        'channelInterpolationMethod',cfg.ChannelInterpolationMethod, ...
        'channelOutOfRangeMode',cfg.ChannelOutOfRangeMode, ...
        'interpolateChannelDelays',logical(cfg.InterpolateChannelDelays), ...
        'equalizerMode',cfg.EqualizerMode, ...
        'AGCEnabled',logical(cfg.AGCEnabled), ...
        'AGCTimeConstantMs',cfg.AGCTimeConstantMs, ...
        'adaptiveEqualizerTaps',cfg.AdaptiveEqualizerTaps, ...
        'adaptiveEqualizerCMAStep',cfg.AdaptiveEqualizerCMAStep, ...
        'adaptiveEqualizerDDStep',cfg.AdaptiveEqualizerDDStep, ...
        'adaptiveEqualizerCMAWarmupSymbols',cfg.AdaptiveEqualizerCMAWarmupSymbols, ...
        'adaptiveEqualizerDDPasses',cfg.AdaptiveEqualizerDDPasses, ...
        'adaptiveEqualizerMaxTapNorm',cfg.AdaptiveEqualizerMaxTapNorm, ...
        'adaptiveEqualizerMinCMAConfidence',cfg.AdaptiveEqualizerMinCMAConfidence, ...
        'adaptiveEqualizerRequireCMAConvergence', ...
            logical(cfg.AdaptiveEqualizerRequireCMAConvergence), ...
        'adaptiveEqualizerQualityGuard', ...
            logical(cfg.AdaptiveEqualizerQualityGuard), ...
        'adaptiveEqualizerMaxMSEDegradation', ...
            cfg.AdaptiveEqualizerMaxMSEDegradation, ...
        'adaptiveEqualizerMSEDegradationMargin', ...
            cfg.AdaptiveEqualizerMSEDegradationMargin, ...
        'adaptiveEqualizerScalarSideTapOnRatio', ...
            cfg.AdaptiveEqualizerScalarSideTapOnRatio, ...
        'adaptiveEqualizerDDWindowSymbols', ...
            cfg.AdaptiveEqualizerDDWindowSymbols, ...
        'adaptiveEqualizerDDMinWindowAcceptance', ...
            cfg.AdaptiveEqualizerDDMinWindowAcceptance, ...
        'adaptiveEqualizerScalarDDPasses', ...
            cfg.AdaptiveEqualizerScalarDDPasses, ...
        'adaptiveEqualizerEnableFadeHold', ...
            logical(cfg.AdaptiveEqualizerEnableFadeHold), ...
        'adaptiveEqualizerEnableQAMWindowHold', ...
            logical(cfg.AdaptiveEqualizerEnableQAMWindowHold), ...
        'adaptiveEqualizerAutoScalarForQAM', ...
            logical(cfg.AdaptiveEqualizerAutoScalarForQAM), ...
        'HasFECF',logical(cfg.HasFECF), ...
        'CRCType',cfg.CRCType, ...
        'FrameSyncBitSlipTolerance',cfg.FrameSyncBitSlipTolerance, ...
        'FrameSyncASMErrorThreshold',cfg.FrameSyncASMErrorThreshold, ...
        'FrameSyncLockThreshold',cfg.FrameSyncLockThreshold, ...
        'FrameSyncUnlockThreshold',cfg.FrameSyncUnlockThreshold);

    if ~isempty(cfg.EqualizerReg)
        p.equalizerReg = double(cfg.EqualizerReg);
    end
    if ~isempty(cfg.AdaptiveEqualizerDecisionGate)
        p.adaptiveEqualizerDecisionGate = double(cfg.AdaptiveEqualizerDecisionGate);
    end
    if ~isempty(cfg.AdaptiveEqualizerCMASwitchMSE)
        p.adaptiveEqualizerCMASwitchMSE = ...
            double(cfg.AdaptiveEqualizerCMASwitchMSE);
    end
    if channel.HEnabled
        p.HMode = 'h_matrix_file';
        p.channelFilePath = channel.File;
    end

    extraNames = fieldnames(coding.Extra);
    for k = 1:numel(extraNames)
        p.(extraNames{k}) = coding.Extra.(extraNames{k});
    end

    if strcmpi(pathMode,'unequalDualIQ')
        p.RRatio = 2;
        p.ARatio = 2;
        p.carrierRecoveryMode = 'uqpsk-teacher';
        p.enableUQPSKFFTCoarseCFO = true;
    end
    if contains(upper(string(modulation)),'APSK')
        p.HasTMAPSKPilots = logical(cfg.UseTMAPSKPilots);
        p.TMAPSKPilotInterval = cfg.TMAPSKPilotInterval;
        p.TMAPSKPilotLength = cfg.TMAPSKPilotLength;
        p.TMAPSKPilotPreambleLength = cfg.TMAPSKPilotPreambleLength;
        p.TMAPSKPilotCorrectionMode = cfg.TMAPSKPilotCorrectionMode;
        p.TMAPSKPilotPhaseSmoothWindow = cfg.TMAPSKPilotPhaseSmoothWindow;
        p.TMAPSKPilotMMSERegularization = cfg.TMAPSKPilotMMSERegularization;
        p.TMAPSKPilotMaxGainDB = cfg.TMAPSKPilotMaxGainDB;
        p.TMAPSKPilotFadeThresholdDB = cfg.TMAPSKPilotFadeThresholdDB;
        p.TMAPSKPilotFadeHold = logical(cfg.TMAPSKPilotFadeHold);
    end
    if strcmpi(modulation,'GMSK')
        p.BandwidthTimeProduct = cfg.GMSKBT;
        p.GMSKDetectionMode = cfg.GMSKDetectionMode;
    end
    if strcmpi(modulation,'MSK')
        p.enableCPMCoarseFrequencyCompensator = logical(cfg.MSKCoarseCFO);
    end
    if cfg.Debug
        p.debugASMPhase = true;
        p.debugCodedBoundary = true;
        p.debugPerFrameBERSummary = logical(cfg.DebugPerFrameBERSummary);
        p.debugGMSK = strcmpi(modulation,'GMSK');
        p.debugMSK = strcmpi(modulation,'MSK');
    end

    name = sprintf('%s_%s_%s_%s_random_%s_%s', ...
        pathMode, modulation, coding.Coding, coding.Rate, ...
        randomizer.Label, channel.Name);
    caseId = "tm.release." + localId(name);
    caseDef = struct( ...
        'Id',caseId, ...
        'Name',string(name), ...
        'Category',"tm_release_matrix", ...
        'Params',p, ...
        'Expected',localExpected(cfg,pathMode,randomizer), ...
        'Meta',struct( ...
            'DataPathMode',string(pathMode), ...
            'Modulation',string(modulation), ...
            'Coding',string(coding.Coding), ...
            'Rate',string(coding.Rate), ...
            'RandomizerEnabled',logical(randomizer.Enabled), ...
            'RandomizerFECPosition',string(randomizer.Position), ...
            'ChannelProfile',string(channel.Name), ...
            'SNR_dB',double(cfg.SNR), ...
            'HEnabled',logical(channel.HEnabled))); 
end

function expected = localExpected(cfg, pathMode, randomizer)
    expected = struct( ...
        'RequiredMetrics',["BER","LockRate"], ...
        'MaxBER',cfg.MaxBER, ...
        'MinLockRate',cfg.MinLockRate, ...
        'MaxFER',cfg.MaxFER, ...
        'MinMERdB',[], ...
        'MinCountedFrames',1, ...
        'ExpectedDataPathMode',string(pathMode), ...
        'ExpectedWaveformMode',"ordinaryTM", ...
        'ExpectedRandomizerFECPosition',string(randomizer.Position), ...
        'ExpectedRandomizerEnabled',logical(randomizer.Enabled), ...
        'ExpectedGMSKDetector',"", ...
        'ExpectedErrorIdentifier',"", ...
        'ExpectedErrorMessage',"");
end

function T = localAttachMetadata(T, cases, cfg)
    n = height(T);
    T.DataPathMode = strings(n,1);
    T.Modulation = strings(n,1);
    T.Coding = strings(n,1);
    T.Rate = strings(n,1);
    T.RandomizerLabel = strings(n,1);
    T.RandomizerEnabled = false(n,1);
    T.RandomizerFECPosition = strings(n,1);
    T.ChannelProfile = strings(n,1);
    T.HEnabled = false(n,1);
    T.FunctionalPass = false(n,1);
    T.FunctionalStatus = strings(n,1);
    T.PerformancePass = logical(T.Pass);
    T.PerformanceStatus = string(T.Status);
    T.SNR_dB = repmat(double(cfg.SNR),n,1);

    for k = 1:n
        meta = cases(k).Meta;
        T.DataPathMode(k) = meta.DataPathMode;
        T.Modulation(k) = meta.Modulation;
        T.Coding(k) = meta.Coding;
        T.Rate(k) = meta.Rate;
        T.RandomizerEnabled(k) = meta.RandomizerEnabled;
        T.RandomizerFECPosition(k) = meta.RandomizerFECPosition;
        T.ChannelProfile(k) = meta.ChannelProfile;
        T.HEnabled(k) = meta.HEnabled;

        if T.Status(k) == "ERROR"
            T.FunctionalStatus(k) = "ERROR";
        elseif isfinite(T.LockRate(k)) && T.LockRate(k) >= cfg.MinLockRate && ...
                isfinite(T.CountedFrames(k)) && T.CountedFrames(k) >= 1
            T.FunctionalPass(k) = true;
            T.FunctionalStatus(k) = "PASS";
        else
            T.FunctionalStatus(k) = "FAIL";
        end
    end

    leading = {'CaseId','Status','Pass','FunctionalStatus','FunctionalPass', ...
        'PerformanceStatus','PerformancePass','DataPathMode','Modulation', ...
        'Coding','Rate','RandomizerEnabled','RandomizerFECPosition', ...
        'ChannelProfile','HEnabled','SNR_dB'};
    T = movevars(T, leading, 'Before', 1);
end

function localWriteJson(T, cfg, plan, pathValue)
    payload = struct( ...
        'Suite',"tm_release_matrix", ...
        'Profile',string(cfg.Profile), ...
        'GeneratedAt',string(datestr(now,'yyyy-mm-dd HH:MM:SS')), ...
        'Plan',plan, ...
        'Cases',table2struct(T));
    outputDir = fileparts(pathValue);
    if ~isfolder(outputDir), mkdir(outputDir); end
    fid = fopen(pathValue,'w');
    assert(fid >= 0, 'Cannot create JSON file: %s', pathValue);
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid,'%s',jsonencode(payload));
    clear cleanup;
end

function localWriteTable(T, pathValue)
    outputDir = fileparts(pathValue);
    if ~isfolder(outputDir), mkdir(outputDir); end
    writetable(T,pathValue);
end

function cases = localEmptyCases()
    cases = struct('Id',{},'Name',{},'Category',{}, ...
        'Params',{},'Expected',{},'Meta',{});
end

function values = localCellstr(value)
    if iscell(value)
        values = cellfun(@char,value,'UniformOutput',false);
    else
        values = cellstr(string(value));
    end
end

function value = localOption(s,name,defaultValue)
    value = defaultValue;
    if isstruct(s) && isfield(s,name) && ~isempty(s.(name))
        value = s.(name);
    end
end

function id = localId(text)
    id = lower(regexprep(string(text),'[^a-zA-Z0-9]+','.'));
    id = strip(id,'.');
end
