function results = run_msk_h_full_h50_json()
%RUN_MSK_H_FULL_H50_JSON
% 7 H files x all TM coding rates x 3 randomizer modes at H=50 dB.
% This runner does not use checkpoints or previous sweep configuration.
% It writes a JSON summary and returns the same struct array.

    outDir = 'E:/web_code/react/fft_project/react-fft/artifacts/ccsds/msk';
    if ~isfolder(outDir)
        mkdir(outDir);
    end

    hFiles = { ...
        'E:/matlab_project/v3.0/v3.0/channel/ChannelData.mat', ...
        'E:/matlab_project/v3.0/v3.0/channel/2-ChannelData.mat', ...
        'E:/matlab_project/v3.0/v3.0/channel/3-ChannelData.mat', ...
        'E:/matlab_project/v3.0/v3.0/channel/4-ChannelData.mat', ...
        'E:/matlab_project/v3.0/v3.0/channel/ChannelData_5.mat', ...
        'E:/matlab_project/v3.0/v3.0/channel/ChannelData_6.mat', ...
        'E:/matlab_project/v3.0/v3.0/channel/ChannelData_7.mat'};

    for k = 1:numel(hFiles)
        assert(isfile(hFiles{k}), 'H 文件不存在：%s', hFiles{k});
    end

    codingCases = localCodingCases();
    randomizers = localRandomizers();
    expectedCases = numel(hFiles) * numel(codingCases) * numel(randomizers);
    assert(expectedCases == 294, ...
        '计划数量错误：实际 %d，预期 294。', expectedCases);

    rowTemplate = struct( ...
        'Modulation','MSK', ...
        'DataPathMode','single', ...
        'CaseId','', ...
        'ChannelFile','', ...
        'ChannelProfile','H_auto_clean50', ...
        'Coding','', ...
        'Rate','', ...
        'RandomizerLabel','', ...
        'RandomizerEnabled',false, ...
        'RandomizerFECPosition','', ...
        'SNR_dB',50, ...
        'CFO_Hz',0, ...
        'PhaseOffset_deg',0, ...
        'Delay_samples',0, ...
        'Seed',NaN, ...
        'Status','', ...
        'BER',NaN, ...
        'LockRate_pct',NaN, ...
        'FER',NaN, ...
        'CountedFrames',NaN, ...
        'ElapsedSeconds',NaN, ...
        'ErrorIdentifier','', ...
        'ErrorMessage','');

    results = repmat(rowTemplate, 0, 1);
    caseCounter = 0;

    for ih = 1:numel(hFiles)
        [~, hName, ~] = fileparts(hFiles{ih});

        for ic = 1:numel(codingCases)
            c = codingCases(ic);

            % Same payload/noise seed for off/after/before of one case.
            pairedSeed = 20260803 + 100000*(ih-1) + 100*(ic-1);

            for ir = 1:numel(randomizers)
                r = randomizers(ir);
                caseCounter = caseCounter + 1;

                row = rowTemplate;
                row.ChannelFile = hFiles{ih};
                row.Coding = c.Coding;
                row.Rate = c.Rate;
                row.RandomizerLabel = r.Label;
                row.RandomizerEnabled = r.Enabled;
                row.RandomizerFECPosition = r.Position;
                row.Seed = pairedSeed;
                row.CaseId = sprintf( ...
                    'msk.%s.h50.%s.%s.random.%s', ...
                    lower(hName), lower(c.Coding), ...
                    strrep(c.Rate, '/', '_'), r.Label);

                fprintf('\n[%03d/%03d] %s\n', ...
                    caseCounter, expectedCases, row.CaseId);

                rng(pairedSeed, 'twister');
                p = localBuildOptions(c, r, hFiles{ih});
                tStart = tic;

                try
                    [m, ~] = run_ccsds_tm_evaluation(p);
                    row.ElapsedSeconds = toc(tStart);

                    if ~isstruct(m)
                        error('MSK:H50ResultType', ...
                            'run_ccsds_tm_evaluation 未返回 metrics struct。');
                    end

                    row.BER = localMetric(m, 'BER', NaN);
                    row.LockRate_pct = 100 * localMetric(m, 'LockRate', NaN);
                    row.FER = localMetric(m, 'FER', NaN);
                    row.CountedFrames = localMetric(m, 'CountedFrames', NaN);

                    if isfinite(row.BER) && row.BER <= 1e-5 && ...
                            isfinite(row.LockRate_pct) && row.LockRate_pct >= 90 && ...
                            isfinite(row.FER) && row.FER <= 1e-5 && ...
                            isfinite(row.CountedFrames) && row.CountedFrames >= 1
                        row.Status = 'PASS';
                    else
                        row.Status = 'FAIL_METRIC';
                    end
                catch ME
                    row.ElapsedSeconds = toc(tStart);
                    row.Status = 'ERROR';
                    row.ErrorIdentifier = char(ME.identifier);
                    row.ErrorMessage = char(ME.message);
                end

                results(end+1, 1) = row; %#ok<AGROW>
                fprintf('[%s] BER=%.6g Lock=%.2f%% FER=%.6g Frames=%.0f Time=%.1fs\n', ...
                    row.Status, row.BER, row.LockRate_pct, row.FER, ...
                    row.CountedFrames, row.ElapsedSeconds);
            end
        end
    end

    jsonFile = fullfile(outDir, ...
        ['msk_h_full_h50_' datestr(now, 'yyyymmdd_HHMMSS') '.json']);
    jsonText = jsonencode(results);
    fid = fopen(jsonFile, 'w');
    assert(fid >= 0, '无法创建 JSON 文件：%s', jsonFile);
    fprintf(fid, '%s', jsonText);
    fclose(fid);

    statuses = {results.Status};
    fprintf('\n===== MSK H full H=50 dB =====\n');
    fprintf('总例数=%d PASS=%d FAIL=%d ERROR=%d\n', ...
        numel(results), nnz(strcmp(statuses, 'PASS')), ...
        nnz(strcmp(statuses, 'FAIL_METRIC')), nnz(strcmp(statuses, 'ERROR')));
    fprintf('JSON: %s\n', jsonFile);
end

function cases = localCodingCases()
    cases = struct('Coding', {}, 'Rate', {}, 'TFBytes', {});
    cases(end+1) = struct('Coding','none', 'Rate','-', 'TFBytes',1115);
    cases(end+1) = struct('Coding','convolutional', 'Rate','1/2', 'TFBytes',1115);
    cases(end+1) = struct('Coding','convolutional', 'Rate','2/3', 'TFBytes',1115);
    cases(end+1) = struct('Coding','convolutional', 'Rate','3/4', 'TFBytes',1115);
    cases(end+1) = struct('Coding','convolutional', 'Rate','5/6', 'TFBytes',1116);
    cases(end+1) = struct('Coding','convolutional', 'Rate','7/8', 'TFBytes',1123);
    cases(end+1) = struct('Coding','RS', 'Rate','223/255', 'TFBytes',1115);
    cases(end+1) = struct('Coding','LDPC', 'Rate','1/2', 'TFBytes',1115);
    cases(end+1) = struct('Coding','LDPC', 'Rate','2/3', 'TFBytes',1115);
    cases(end+1) = struct('Coding','LDPC', 'Rate','4/5', 'TFBytes',1115);
    cases(end+1) = struct('Coding','turbo', 'Rate','1/2', 'TFBytes',1115);
    cases(end+1) = struct('Coding','turbo', 'Rate','1/3', 'TFBytes',1115);
    cases(end+1) = struct('Coding','turbo', 'Rate','1/4', 'TFBytes',1115);
    cases(end+1) = struct('Coding','turbo', 'Rate','1/6', 'TFBytes',1115);
end

function r = localRandomizers()
    r = struct('Label', {}, 'Enabled', {}, 'Position', {});
    r(end+1) = struct('Label','off', 'Enabled',false, 'Position','afterEncoding');
    r(end+1) = struct('Label','after', 'Enabled',true, 'Position','afterEncoding');
    r(end+1) = struct('Label','before', 'Enabled',true, 'Position','beforeEncoding');
end

function p = localBuildOptions(c, r, hFile)
    p = struct( ...
        'modType','MSK', ...
        'DataPathMode','single', ...
        'symbolRate',1e6, ...
        'sps',8, ...
        'snr',50, ...
        'cfo',0, ...
        'phaseOffset',0, ...
        'delay',0, ...
        'channelCoding',c.Coding, ...
        'NumBytesInTransferFrame',c.TFBytes, ...
        'RandomizerEnabled',r.Enabled, ...
        'RandomizerFECPosition',r.Position, ...
        'hasASM',true, ...
        'enableCPMCoarseFrequencyCompensator',false, ...
        'enableHChannel',true, ...
        'HMode','h_matrix_file', ...
        'channelFilePath',hFile, ...
        'channelInterpolationMethod','linear', ...
        'channelOutOfRangeMode','wrap', ...
        'interpolateChannelDelays',false, ...
        'normalizeHChannel',false, ...
        'enableEqualizer',true, ...
        'equalizerMode','mmse', ...
        'normalizeEqualizerOutput',true, ...
        'berWarmUpFrames',4, ...
        'berFrames',16, ...
        'debugMSK',false, ...
        'debugASMPhase',false, ...
        'debugCodedBoundary',false, ...
        'showFigures',false);

    if strcmpi(c.Coding, 'convolutional')
        p.ConvolutionalCodeRate = c.Rate;
    elseif strcmpi(c.Coding, 'LDPC') || strcmpi(c.Coding, 'turbo')
        p.CodeRate = c.Rate;
    end
end

function value = localMetric(m, name, defaultValue)
    value = defaultValue;
    if isstruct(m) && isfield(m, name)
        candidate = m.(name);
        if isnumeric(candidate) && isscalar(candidate)
            value = double(candidate);
        end
    end
end
