function T = run_tm_apsk_dualiq_validation(stage, userOpts)
%RUN_TM_APSK_DUALIQ_VALIDATION Standalone APSK ordinary-TM dual-I/Q sweep.
%
% This entry never reads variables left in the MATLAB base workspace.
%
% Full no-H coding/rate/randomizer matrix (78 cases):
%   T = run_tm_apsk_dualiq_validation('noH-full');
%
% Seven H models, four representative codings (168 cases):
%   T = run_tm_apsk_dualiq_validation('H-representative');
%
% Seven H models, every formal coding/rate (546 cases):
%   T = run_tm_apsk_dualiq_validation('H-full');

    if nargin < 1 || isempty(stage)
        stage = 'noH-full';
    end
    if nargin < 2 || isempty(userOpts)
        userOpts = struct();
    end
    if ~isstruct(userOpts)
        error('run_tm_apsk_dualiq_validation:InvalidOptions', ...
            'userOpts must be a struct.');
    end

    thisDir = fileparts(mfilename('fullpath'));
    sourceDir = fileparts(thisDir);
    addpath(thisDir);
    addpath(sourceDir);

    stage = lower(string(stage));
    validStages = ["noh-full","h-representative","h-full"];
    if ~isscalar(stage) || ~any(stage == validStages)
        error('run_tm_apsk_dualiq_validation:InvalidStage', ...
            'stage must be noH-full, H-representative, or H-full.');
    end

    cfg = struct( ...
        'RunId','', ...
        'Resume',true, ...
        'RerunFailed',false, ...
        'DryRun',false, ...
        'MaxNewCases',Inf, ...
        'BaseSeed',20260730, ...
        'FailOnFailure',false, ...
        'Verbose',true, ...
        'SNR',50, ...
        'CFO',0, ...
        'PhaseOffset',0, ...
        'Delay',0, ...
        'SymbolRate',1e6, ...
        'SamplesPerSymbol',8, ...
        'BERWarmUpFrames',8, ...
        'BERFrames',16, ...
        'MaxBER',1e-5, ...
        'MinLockRate',0.90, ...
        'MaxFER',1e-5, ...
        'ChannelDir','E:/matlab_project/v3.0/v3.0/channel');
    names = fieldnames(userOpts);
    for k = 1:numel(names)
        name = names{k};
        if ~isfield(cfg, name)
            error('run_tm_apsk_dualiq_validation:UnknownOption', ...
                'Unknown option "%s".', name);
        end
        cfg.(name) = userOpts.(name);
    end

    if isempty(cfg.RunId)
        token = sprintf('%s_snr%g_cfo%g_phase%g_delay%g', ...
            char(stage), cfg.SNR, cfg.CFO, cfg.PhaseOffset, cfg.Delay);
        token = lower(regexprep(token, '[^a-zA-Z0-9]+', '_'));
        cfg.RunId = ['apsk_dualiq_', token, '_v1'];
    end

    randomizers = struct('Label',{},'Enabled',{},'Position',{});
    randomizers(1) = struct( ...
        'Label',"off",'Enabled',false,'Position',"afterEncoding");
    randomizers(2) = struct( ...
        'Label',"after",'Enabled',true,'Position',"afterEncoding");
    randomizers(3) = struct( ...
        'Label',"before",'Enabled',true,'Position',"beforeEncoding");

    if stage == "noh-full"
        noH = struct('enableHChannel',false,'enableEqualizer',false);
        profiles = struct( ...
            'Name',"noH_clean", ...
            'SNR',cfg.SNR, ...
            'CFO',cfg.CFO, ...
            'PhaseOffset',cfg.PhaseOffset, ...
            'Delay',cfg.Delay, ...
            'Extra',noH);
        [convRates, ldpcRates, turboRates] = localFullRates();
        expectedCases = 78;
    else
        profiles = localHProfiles(cfg);
        if stage == "h-representative"
            convRates = {'1/2'};
            ldpcRates = {'1/2'};
            turboRates = {'1/2'};
            expectedCases = 168;
        else
            [convRates, ldpcRates, turboRates] = localFullRates();
            expectedCases = 546;
        end
    end

    opts = struct();
    opts.RunId = char(cfg.RunId);
    opts.Resume = logical(cfg.Resume);
    opts.RerunFailed = logical(cfg.RerunFailed);
    opts.FailOnFailure = logical(cfg.FailOnFailure);
    opts.Verbose = logical(cfg.Verbose);
    opts.MaxNewCases = double(cfg.MaxNewCases);
    opts.DryRun = logical(cfg.DryRun);
    opts.BaseSeed = double(cfg.BaseSeed);
    opts.SeedMode = 'pairedChannelProfile';
    opts.SymbolRate = double(cfg.SymbolRate);
    opts.SamplesPerSymbol = double(cfg.SamplesPerSymbol);
    opts.BERWarmUpFrames = double(cfg.BERWarmUpFrames);
    opts.BERFrames = double(cfg.BERFrames);
    opts.DataPathModes = {'dualIQ'};
    opts.DualIQModulations = {'16APSK','32APSK'};
    opts.SingleExtraModulations = {};
    opts.ConvolutionalRates = convRates;
    opts.LDPCRates = ldpcRates;
    opts.TurboRates = turboRates;
    opts.RandomizerCases = randomizers;
    opts.ChannelProfiles = profiles;
    opts.IncludeUncoded = false;
    opts.IncludeOrdinaryTMAPSK = false;
    opts.SplitPathDebug = false;
    opts.EvaluationOverrides = struct( ...
        'showFigures',false, ...
        'HasTMAPSKPilots',true, ...
        'UseSplitReceiverCoordinator',true);
    opts.CaseIds = strings(0,1);
    opts.SelectedOnlyPlan = false;
    opts.MaxBER = double(cfg.MaxBER);
    opts.MinLockRate = double(cfg.MinLockRate);
    opts.MaxFER = double(cfg.MaxFER);

    T = run_tm_data_path_sweep('deep', opts);
    if height(T) ~= expectedCases
        error('run_tm_apsk_dualiq_validation:UnexpectedCaseCount', ...
            'Expected %d cases but the plan contains %d.', ...
            expectedCases, height(T));
    end

    fprintf('\nAPSK dual-I/Q %s: PASS=%d FAIL=%d ERROR=%d PENDING=%d\n', ...
        char(stage), nnz(T.Status == "PASS"), ...
        nnz(T.Status == "FAIL_METRIC"), nnz(T.Status == "ERROR"), ...
        nnz(T.Status == "PENDING"));
    disp(groupcounts(T, {'Modulation','Coding','ChannelProfile','Status'}));
end

function [convRates, ldpcRates, turboRates] = localFullRates()
    convRates = {'1/2','2/3','3/4','5/6','7/8'};
    ldpcRates = {'1/2','2/3','4/5'};
    turboRates = {'1/2','1/3','1/4','1/6'};
end

function profiles = localHProfiles(cfg)
    channelDir = char(string(cfg.ChannelDir));
    channelRows = { ...
        'TDL',       '2-ChannelData.mat'; ...
        'CDL',       '3-ChannelData.mat'; ...
        'ITU_P681',  '4-ChannelData.mat'; ...
        'Jakes',     'ChannelData_5.mat'; ...
        'CLoo',      'ChannelData_6.mat'; ...
        'Corazza',   'ChannelData_7.mat'; ...
        'Lutz',      'ChannelData_8.mat'};

    profiles = struct( ...
        'Name',{},'SNR',{},'CFO',{},'PhaseOffset',{},'Delay',{},'Extra',{});
    for k = 1:size(channelRows,1)
        channelFile = fullfile(channelDir, channelRows{k,2});
        if exist(channelFile, 'file') ~= 2
            error('run_tm_apsk_dualiq_validation:MissingChannelFile', ...
                'Missing H channel file: %s', channelFile);
        end
        hAuto = struct( ...
            'enableHChannel',true, ...
            'HMode','h_matrix_file', ...
            'channelFilePath',channelFile, ...
            'channelInterpolationMethod','linear', ...
            'channelOutOfRangeMode','wrap', ...
            'interpolateChannelDelays',false, ...
            'normalizeHChannel',false, ...
            'enableEqualizer',true, ...
            'equalizerMode','mmse', ...
            'normalizeEqualizerOutput',true);
        profiles(end+1) = struct( ... %#ok<AGROW>
            'Name',string(channelRows{k,1}), ...
            'SNR',cfg.SNR, ...
            'CFO',cfg.CFO, ...
            'PhaseOffset',cfg.PhaseOffset, ...
            'Delay',cfg.Delay, ...
            'Extra',hAuto);
    end
end
