function T = run_tm_apsk_tdl_snr_ladder(userOpts)
%RUN_TM_APSK_TDL_SNR_LADDER Characterize the remaining TDL coding margin.
%
%   T = run_tm_apsk_tdl_snr_ladder;
%
% Runs 24 independent ordinary-TM dual-I/Q cases:
%   16APSK/32APSK x convolutional 1/2 x three randomizer modes
%   x SNR=[35 40 45 50] dB through TDL, with CFO=20 kHz,
%   phase=10 deg, delay=0.2 sample, MMSE equalization and APSK coarse CFO.
%
% The entry owns every parameter and does not read the MATLAB base workspace.

    if nargin < 1 || isempty(userOpts)
        userOpts = struct();
    end
    if ~isstruct(userOpts)
        error('run_tm_apsk_tdl_snr_ladder:InvalidOptions', ...
            'userOpts must be a struct.');
    end

    thisDir = fileparts(mfilename('fullpath'));
    sourceDir = fileparts(thisDir);
    addpath(thisDir);
    addpath(sourceDir);

    cfg = struct( ...
        'RunId','apsk_tdl_conv12_snr_ladder_cfo20k_v1', ...
        'Resume',true, ...
        'RerunFailed',false, ...
        'DryRun',false, ...
        'MaxNewCases',Inf, ...
        'BaseSeed',20260730, ...
        'FailOnFailure',false, ...
        'Verbose',true, ...
        'SNRValues',[35 40 45 50], ...
        'CFO',20000, ...
        'PhaseOffset',10, ...
        'Delay',0.2, ...
        'SymbolRate',1e6, ...
        'SamplesPerSymbol',8, ...
        'BERWarmUpFrames',8, ...
        'BERFrames',16, ...
        'MaxBER',1e-5, ...
        'MinLockRate',0.90, ...
        'MaxFER',1e-5, ...
        'ChannelFile','E:/matlab_project/v3.0/v3.0/channel/2-ChannelData.mat');
    cfg = localApplyOptions(cfg, userOpts);

    snrValues = double(cfg.SNRValues(:).');
    validateattributes(snrValues, {'numeric'}, {'nonempty','finite','real'});
    if exist(char(cfg.ChannelFile), 'file') ~= 2
        error('run_tm_apsk_tdl_snr_ladder:MissingChannelFile', ...
            'Missing TDL channel file: %s', char(cfg.ChannelFile));
    end

    profiles = struct('Name',{},'SNR',{},'CFO',{}, ...
        'PhaseOffset',{},'Delay',{},'Extra',{});
    for k = 1:numel(snrValues)
        hAuto = struct( ...
            'enableHChannel',true, ...
            'HMode','h_matrix_file', ...
            'channelFilePath',char(cfg.ChannelFile), ...
            'channelInterpolationMethod','linear', ...
            'channelOutOfRangeMode','wrap', ...
            'interpolateChannelDelays',false, ...
            'normalizeHChannel',false, ...
            'enableEqualizer',true, ...
            'equalizerMode','mmse', ...
            'normalizeEqualizerOutput',true);
        profiles(end+1) = struct( ... %#ok<AGROW>
            'Name',"TDL_snr" + string(snrValues(k)), ...
            'SNR',snrValues(k), ...
            'CFO',double(cfg.CFO), ...
            'PhaseOffset',double(cfg.PhaseOffset), ...
            'Delay',double(cfg.Delay), ...
            'Extra',hAuto);
    end

    randomizers = struct('Label',{},'Enabled',{},'Position',{});
    randomizers(1) = struct('Label',"off",'Enabled',false, ...
        'Position',"afterEncoding");
    randomizers(2) = struct('Label',"after",'Enabled',true, ...
        'Position',"afterEncoding");
    randomizers(3) = struct('Label',"before",'Enabled',true, ...
        'Position',"beforeEncoding");

    opts = struct();
    opts.RunId = char(cfg.RunId);
    opts.Resume = logical(cfg.Resume);
    opts.RerunFailed = logical(cfg.RerunFailed);
    opts.FailOnFailure = logical(cfg.FailOnFailure);
    opts.Verbose = logical(cfg.Verbose);
    opts.MaxNewCases = double(cfg.MaxNewCases);
    opts.DryRun = logical(cfg.DryRun);
    opts.BaseSeed = double(cfg.BaseSeed);
    opts.SeedMode = 'pairedChannelProfile';
    opts.SymbolRate = double(cfg.SymbolRate);
    opts.SamplesPerSymbol = double(cfg.SamplesPerSymbol);
    opts.BERWarmUpFrames = double(cfg.BERWarmUpFrames);
    opts.BERFrames = double(cfg.BERFrames);
    opts.DataPathModes = {'dualIQ'};
    opts.DualIQModulations = {'16APSK','32APSK'};
    opts.SingleExtraModulations = {};
    opts.ConvolutionalRates = {'1/2'};
    opts.LDPCRates = {};
    opts.TurboRates = {};
    opts.RandomizerCases = randomizers;
    opts.ChannelProfiles = profiles;
    opts.IncludeUncoded = false;
    opts.IncludeOrdinaryTMAPSK = false;
    opts.SplitPathDebug = false;
    opts.EvaluationOverrides = struct( ...
        'showFigures',false, ...
        'HasTMAPSKPilots',true, ...
        'UseSplitReceiverCoordinator',true, ...
        'enableAPSKCoarseFrequencyCompensator',true);
    % run_tm_data_path_sweep also includes RS in every formal plan.  This
    % ladder is deliberately convolutional-only, so select its 24 IDs
    % explicitly rather than spending time on unrelated RS controls.
    opts.CaseIds = localConvolutionalCaseIds(snrValues, randomizers);
    opts.SelectedOnlyPlan = true;
    opts.MaxBER = double(cfg.MaxBER);
    opts.MinLockRate = double(cfg.MinLockRate);
    opts.MaxFER = double(cfg.MaxFER);

    T = run_tm_data_path_sweep('deep', opts);
    expectedCases = 2 * 3 * numel(snrValues);
    if height(T) ~= expectedCases
        error('run_tm_apsk_tdl_snr_ladder:UnexpectedCaseCount', ...
            'Expected %d cases but the plan contains %d.', expectedCases, height(T));
    end

    fprintf('\nAPSK TDL convolutional 1/2 SNR ladder: PASS=%d FAIL=%d ERROR=%d PENDING=%d\n', ...
        nnz(T.Status == "PASS"), nnz(T.Status == "FAIL_METRIC"), ...
        nnz(T.Status == "ERROR"), nnz(T.Status == "PENDING"));
    disp(T(:, {'Modulation','RandomizerEnabled','RandomizerFECPosition', ...
        'ChannelProfile','Status','BER','LockRate_pct','FER', ...
        'MER_dB','EVM_post_pct'}));
end

function caseIds = localConvolutionalCaseIds(snrValues, randomizers)
    caseIds = strings(0,1);
    for iSNR = 1:numel(snrValues)
        channelName = "TDL_snr" + string(snrValues(iSNR));
        for iMod = 1:2
            modulation = ["16APSK","32APSK"];
            for iRandomizer = 1:numel(randomizers)
                name = sprintf('dualIQ_%s_convolutional_1/2_random_%s_%s', ...
                    modulation(iMod), char(randomizers(iRandomizer).Label), ...
                    char(channelName));
                token = lower(regexprep(string(name), '[^a-zA-Z0-9]+', '.'));
                token = strip(token, '.');
                caseIds(end+1,1) = "tm.path." + token; %#ok<AGROW>
            end
        end
    end
end

function cfg = localApplyOptions(cfg, userOpts)
    names = fieldnames(userOpts);
    for k = 1:numel(names)
        name = names{k};
        if ~isfield(cfg, name)
            error('run_tm_apsk_tdl_snr_ladder:UnknownOption', ...
                'Unknown option "%s".', name);
        end
        cfg.(name) = userOpts.(name);
    end
end
